// Dynamic on-the-fly AI Translation System powered by Gemini
import { Language } from "../types";

// In-memory cache to prevent redundant API translations
const translationCache: Record<string, string> = {};

// Instant high-fidelity lookup dictionary for modals and core layout pages to guarantee 100% reliable, zero-latency translations
export const OFFLINE_TEXT_DICTIONARY: Record<string, Record<string, string>> = {
  fa: {
    "💎 Upgrade to Melkban Gold Agency Panel": "💎 ارتقا به پنل کارگزاری طلایی ملکان",
    "Go global, access real-time forex indices & utilize unlimited AI engine configurations.": "با پیوستن به کانون طلایی کاداستر، ملکتان را جهانی و معاملات را چندبرابر سرعت ببخشید.",
    "GOLD PREMIUM PERKS": "امکانات فرامحلی اشتراک طلایی",
    "Live Global Forex Desk": "تسعیر و تبدیل زنده تمام ارزهای جهان",
    "Convert property deeds into Dollar, Euro, Dirham, Afghan Afghani & Turkish Lira instantly.": "نمایش خودکار قیمت و تبدیل سند به ۱۲ ارز زنده (دلار، درهم، یورو، لیر لیر، روبل، افغانی...) در چند ثانیه",
    "Unlimited Active Postings": "نامحدود کردن ظرفیت ثبت آگهی ملکی",
    "Bypass the 2-listing limitation completely. Host an endless catalog of premium cadastral items.": "برداشته شدن کامل حد ثبت آگهی‌های کارگزاری (بدون نیاز به پرداخت کارمزدهای مکرر بابت هر فایل)",
    "4-Engine AI Consultation Suite": "دسترسی نامحدود به ۴ مدل هوش مصنوعی",
    "Unlock expert investment ROIs, materials checkups, and area statistical breakdowns.": "مشاوره اقتصادی ۵ ساله، تحلیل ساختاری سازه، تخمین کاداستر و آمارهای محلی با هوش مصنوعی پیشرفته Gemini",
    "Gold Verified Trusted Badge": "نشان طلایی رسمی «کارگزار معتمد»",
    "Instill supreme buyer trust. Get labeled as a verified municipal broker with golden checkmarks.": "به نمایش درآمدن نشان طلایی کاداستر کنار پروفایل شما جهت افزایش جلب اطمینان خریداران تا ۱۴۰٪",
    "Advanced Export Options": "دانلود گزارشات با PDF و Excel",
    "Compile valuation portfolios into presentable client documents with customizable contact grids.": "استخراج یک‌کلیکه تحلیل منطقه‌ای و سبد اسناد کلاینت برای خروجی‌های حرفه‌ای چاپی و اکسل",
    "ACTIVATION DETAILS": "جزئیات فعال‌سازی و فاکتور",
    "✉️ Broker Account Email:": "✉️ ایمیل اکانت کارگزاری:",
    "💳 Select Secure Checkout Method:": "💳 انتخاب شیوه پرداخت ایمن:",
    "Debit Card": "کارت عضو شتاب",
    "Tether USDT": "ارز دیجیتال (Tether)",
    "Gold Base Subscription:": "تعرفه عضویت طلایی پایه:",
    "🎁 Global Site Discount:": "🎁 تخفیف عمومی سراسری سایت:",
    "🎫 Your Promo Code Discount:": "🎫 تخفیف کد معرف/پروموشن شما:",
    "Net Payable Total:": "مبلغ قابل پرداخت نهایی:",
    "🎫 Special Promo Code:": "🎫 کد تخفیف ویژه (پروموشن):",
    "Verify": "بررسی",
    "💳 Destination Admin Bank Card Number:": "💳 کُد ۱۶ رقمی کارت بانکی شتاب مقصد (مدیریت سایت):",
    "✓ Transfer subscription fee to the admin card above and input your sender card info below.": "✓ وجه اشتراک را به کارت مدیریت فوق واریز کرده و سپس مشخصات فیش/کارت خود را زیر بنویسید.",
    "👤 Your 16-Digit Sender Card Number:": "👤 کُد ۱۶ رقمی کارت بانکی شتاب فرستنده (شما):",
    "👤 Cardholder Name:": "👤 نام صاحب کارت بانکی:",
    "📸 Upload Transfer Document (Receipt/Slip Photo):": "📸 آپلود تصویر یا فایل سند انتقالی (فیش/رسید واریز):",
    "Document attached successfully": "رسید انتقال ضمیمه شد",
    "Click to select or drag & drop slip file": "جهت بارگذاری کلیک کنید یا فایل را بکشید",
    "(Allowed types: JPG, PNG, PDF)": "(فرمت‌های مجاز: JPG, PNG, PDF)",
    "USDT address (TRC-20):": "آدرس پرداخت تتر شبکه (TRC-20):",
    "✓ Deposit USDT inside the cadastral vault and trigger approval ledger.": "✓ پس از واریز تتر به ولت سامانه فوق، کلید تایید نهایی پایینی را فشار دهید.",
    "💡 Cadastral cloud profiles are compiled in local sandbox caching and dynamic system memory, instantly upgrading server responses across and updating layouts.": "💡 گواهینامه اشتراک کاداستر با پایداری چندگانه ابری فعال می‌شود. این لایه شبیه‌ساز پرداخت، قابلیت ارتقای ۱۰۰ درصدی ایمیل شما را در کل اپ ملکتان به صورت داینامیک فراهم می‌کند.",
    "Cancel": "انصراف",
    "Submit & Launch Gold Pro Class": "تکمیل و راه‌اندازی اشتراک طلایی",
    "Verifying & Committing Golden Ledger...": "در حال تایید و ثبت فاکتور طلایی...",
    "🎉 Congratulations! Ariana Gold Subscription Activated!": "🎉 تبریک! اشتراک طلایی آریانا با موفقیت فعال شد!",
    "Your real estate agency account is now in Gold premium status. Live world exchange rates, specialized AI engines, and limitless listings are fully unlocked.": "بنگاه معاملات ملکی شما به سطح طلایی ارتقا یافت. هم‌اکنون دسترسی به تبدیل اسعار زنده جهانی خلیج فارس و اروپا، ۴ موتور هوش مصنوعی Gemini و ثبت آگهی‌های نامحدود برای شما باز شده است.",
    "Active Member Profile:": "شناسه کاربری طلایی:",
    "Access Level:": "ردیف عضویت:",
    "GOLD CADASTRAL PRO": "وی‌آی‌پی طلایی (GOLD PRO)",
    "Expires at:": "اعتبار قانونی:",
    "Excellent, Start Using Gold Features": "دمت گرم، شروع استفاده از خدمات طلایی کاداستر",
    "🛡️ Continuous blockchain encryption & municipal standard validation is guaranteed.": "🛡️ تسعیر توسط بانک‌های مرکزی و صرافی‌های فرابورس تایید شده است.",
    "Install App": "نصب برنامه",
    "Install Our App": "نصب برنامه یا میانبر",
    "Install our fast web-app shortcut registry. Gain instant, non-browser entry to cadastral maps and AI assistants with a dedicated application icon on your homescreen.": "کلید میانبر کاداستر فوق‌العاده سریع را روی صفحه خود نصب کنید تا نیازی به باز کردن مکرر مرورگر نداشته باشید و به تمام نقشه‌ها دسترسی همیشگی پیدا کنید.",
    "Google Sandbox Frame Active": "فهرست امنیتی گوگل سندباکس فعال است",
    "Direct PWA installation handles are disabled inside nested sandboxed frames due to Chrome security policies inside iframe. Press the golden button below to launch an independent browser context, open in a new tab, and install instantly.": "امکان نصب مستقیم میانبر به دلیل اجرای برنامه در فریم امنیتی گوگل محدود شده است. کلید طلایی زیر را فشار دهید تا برنامه در صفحه مستقل باز شده و بلافاصله نصب شود.",
    "Launch Standalone & Install Easily": "راه‌اندازی صفحه مستقل و نصب آسان",
    "Open this page in Safari browser, then tap the 'Share' tool at the bottom.": "این صفحه را حتماً در مرورگر سافاری (Safari) باز کرده و دکمه اشتراک‌گذاری دایره‌ای پایین را بزنید.",
    "Scroll down the list and select the 'Add to Home Screen' action.": "در لیست باز شده، گزینه افزودن به صفحه اصلی (Add to Home Screen) را پیدا کرده و انتخاب کنید.",
    "Click 'Add' on the upper corner of your screen to conclude setting the shortcut.": "روی دکمه افزودن (Add) در گوشه بالای صفحه کلیک کنید تا میانبر کاداستر ایجاد شود.",
    "Click our green 'Install' header button, or expand the browser menu button (⋮).": "روی دکمه سبز رنگ میانبر کلیک کرده یا منوی سه‌نقطه (⋮) مرورگر خود را باز کنید.",
    "Locate and toggle the 'Install app' or 'Add to Home screen' trigger.": "گزینه نصب برنامه (Install app) یا افزودن به صفحه کار خود را انتخاب کنید.",
    "Confirm the prompt. The operating system will complete setup as a standalone tool!": "تایید نهایی را فشار دهید. سیستم‌عامل شما به شکل کاملاً مجزا برنامه را به صفحه گوشی شما اضافه می‌کند.",
    "No Desktop Shortcut on Windows 11?": "میانبر در وندور ویندوز ایجاد نشد؟",
    "Windows Chrome installs PWAs quietly. If missing on desktop: open chrome://apps in Chrome, right-click 'Melkban' -> 'Create shortcut' -> check 'Desktop'. Or simply search for the app name in your Windows Start Menu.": "کروم ویندوز برنامه‌ها را بی‌صدا ذخیره می‌کند. اگر پیدایش نکردید، عبارت chrome://apps را باز کرده، روی آیکون Melkban راست کلیک کرده و ایجاد میانبر دسکتاپ را فعال کنید.",
    "Got it": "فهمیدم، بستن راهنما",
    "Install Instantly": "شروع نصب فوری",
  },
  tr: {
    "💎 Upgrade to Melkban Gold Agency Panel": "💎 Melkban Gold Acente Paneline Yükselt",
    "Go global, access real-time forex indices & utilize unlimited AI engine configurations.": "Küresel hale gelin, gerçek zamanlı döviz endekslerine erişin ve sınırsız yapay zeka yapılandırması kullanın.",
    "GOLD PREMIUM PERKS": "GOLD PREMIUM AYRICALIKLARI",
    "Live Global Forex Desk": "Canlı Küresel Döviz Masası",
    "Convert property deeds into Dollar, Euro, Dirham, Afghan Afghani & Turkish Lira instantly.": "Tapu senetlerini anında Dolar, Euro, Dirhem ve Türk Lirası'na dönüştürün.",
    "Unlimited Active Postings": "Sınırsız Aktif İlan Yayını",
    "Bypass the 2-listing limitation completely. Host an endless catalog of premium cadastral items.": "2 ilan sınırını tamamen kaldırın. Sonsuz gayrimenkul portföyü yayınlayın.",
    "4-Engine AI Consultation Suite": "4 Motorlu AI Danışmanlık Paketi",
    "Unlock expert investment ROIs, materials checkups, and area statistical breakdowns.": "Uzman yatırım analizleri, malzeme incelemeleri ve bölgesel istatistikleri açın.",
    "Gold Verified Trusted Badge": "Gold Doğrulanmış Güvenilir Rozeti",
    "Instill supreme buyer trust. Get labeled as a verified municipal broker with golden checkmarks.": "Alıcı güvenini zirveye çıkarın. Altın onay işaretiyle güvenilir broker olun.",
    "Advanced Export Options": "Gelişmiş Dışa Aktarma Seçenekleri",
    "Compile valuation portfolios into presentable client documents with customizable contact grids.": "Bölgesel analiz portföylerini tek tıkla PDF veya Excel olarak dışa aktarın.",
    "ACTIVATION DETAILS": "AKTİVASYON DETAYLARI VE FATURA",
    "✉️ Broker Account Email:": "✉️ Broker Hesabı E-postası:",
    "💳 Select Secure Checkout Method:": "💳 Güvenli Ödeme Yöntemi Seçin:",
    "Debit Card": "Banka Kartı (Shetab)",
    "Tether USDT": "Kripto Ödeme (USDT)",
    "Gold Base Subscription:": "Temel Gold Üyelik Ücreti:",
    "🎁 Global Site Discount:": "🎁 Genel Site İndirimi:",
    "🎫 Your Promo Code Discount:": "🎫 Promosyon Kodu İndiriminiz:",
    "Net Payable Total:": "Net Ödenecek Tutar:",
    "🎫 Special Promo Code:": "🎫 Özel Promosyon Kodu:",
    "Verify": "Doğrula",
    "💳 Destination Admin Bank Card Number:": "💳 Alıcı Yönetici Banka Kartı Numarası:",
    "✓ Transfer subscription fee to the admin card above and input your sender card info below.": "✓ Ücreti yukarıdaki yönetici kartına aktarın ve gönderici bilgilerinizi aşağıya girin.",
    "👤 Your 16-Digit Sender Card Number:": "👤 16 Haneli Gönderici Kartı Numaranız:",
    "👤 Cardholder Name:": "👤 Kart Sahibi Adı:",
    "📸 Upload Transfer Document (Receipt/Slip Photo):": "📸 Ödeme Belgesi / Dekont Yükle:",
    "Document attached successfully": "Dekont başarıyla yüklendi",
    "Click to select or drag & drop slip file": "Yüklemek için tıklayın veya dosyayı sürükleyin",
    "(Allowed types: JPG, PNG, PDF)": "(İzin verilen türler: JPG, PNG, PDF)",
    "USDT address (TRC-20):": "USDT Ödeme Adresi (TRC-20):",
    "✓ Deposit USDT inside the cadastral vault and trigger approval ledger.": "✓ Tether transferini yapın ve aşağıdaki tescil butonuna tıklayın.",
    "💡 Cadastral cloud profiles are compiled in local sandbox caching and dynamic system memory, instantly upgrading server responses across and updating layouts.": "💡 Kataster bulut profili entegrasyonu anında hesabınızı günceller.",
    "Cancel": "Vazgeç",
    "Submit & Launch Gold Pro Class": "Ödemeyi Gönder ve Gold Pro'yu Başlat",
    "Verifying & Committing Golden Ledger...": "Altın Hesap Doğrulanıyor...",
    "🎉 Congratulations! Ariana Gold Subscription Activated!": "🎉 Tebrikler! Gold Üyeliğiniz Aktive Edildi!",
    "Your real estate agency account is now in Gold premium status. Live world exchange rates, specialized AI engines, and limitless listings are fully unlocked.": "Hesabınız Gold statüsüne yükseltildi. Sınırsız ilanlar ve AI özellikleri açıldı.",
    "Active Member Profile:": "Aktif Üye Profili:",
    "Access Level:": "Erişim Seviyesi:",
    "GOLD CADASTRAL PRO": "GOLD PREMİUM PRO",
    "Expires at:": "Geçerlilik Tarihi:",
    "Excellent, Start Using Gold Features": "Harika, Altın Özellikleri Kullanmaya Başla",
    "🛡️ Continuous blockchain encryption & municipal standard validation is guaranteed.": "🛡️ Kesintisiz blockchain şifrelemesi ve resmi onay garanti altındadır.",
    "Install App": "Uygulamayı Yükle",
    "Install Our App": "Uygulamayı Yükle",
    "Install our fast web-app shortcut registry. Gain instant, non-browser entry to cadastral maps and AI assistants with a dedicated application icon on your homescreen.": "Hızlı kısayol uygulamamızı yükleyin ve tarayıcı kullanmadan haritalar ve yapay zeka asistanlarına anında erişin.",
    "Google Sandbox Frame Active": "Google Sandbox Koruması Aktif",
    "Direct PWA installation handles are disabled inside nested sandboxed frames due to Chrome security policies inside iframe. Press the golden button below to launch an independent browser context, open in a new tab, and install instantly.": "Doğrudan PWA kurulumu güvenlik politikaları nedeniyle engellenmiştir. Bağımsız sayfada açıp yüklemek için aşağıdaki altın butona basın.",
    "Launch Standalone & Install Easily": "Ayrı Sayfada Aç ve Kolayca Yükle",
    "Open this page in Safari browser, then tap the 'Share' tool at the bottom.": "Safay üzerinde bu sayfayı açın ve alttaki Paylaş butonuna dokunun.",
    "Scroll down the list and select the 'Add to Home Screen' action.": "Açılan menüden 'Ana Ekrana Ekle' seçeneğini seçin.",
    "Click 'Add' on the upper corner of your screen to conclude setting the shortcut.": "Ekranın sağ üstündeki 'Ekle'ye tıklayarak kısayolu oluşturun.",
    "Click our green 'Install' header button, or expand the browser menu button (⋮).": "Header'daki yeşil 'Yükle' butonuna basın veya tarayıcı menüsünü (⋮) açın.",
    "Locate and toggle the 'Install app' or 'Add to Home screen' trigger.": "'Uygulamayı yükle' veya 'Ana ekrana ekle' seçeneğini bulun.",
    "Confirm the prompt. The operating system will complete setup as a standalone tool!": "Ekrana gelen bildirimi onaylayarak bağımsız kurulumu tamamlayın.",
    "No Desktop Shortcut on Windows 11?": "Masaüstü kısayolu görünmüyor mu?",
    "Windows Chrome installs PWAs quietly. If missing on desktop: open chrome://apps in Chrome, right-click 'Melkban' -> 'Create shortcut' -> check 'Desktop'. Or simply search for the app name in your Windows Start Menu.": "Chrome uygulamayı sessizce yükler. Desktop'ta yoksa chrome://apps yazarak kısayol oluşturun.",
    "Got it": "Tamam, Anladım",
    "Install Instantly": "Anında Kurulum",
  },
  ar: {
    "💎 Upgrade to Melkban Gold Agency Panel": "💎 الترقية إلى لوحة الوكالة الذهبية لملک‌بان",
    "Go global, access real-time forex indices & utilize unlimited AI engine configurations.": "انطلق عالمياً، واحصل على أسعار صرف حية واستفد من حزمة الذكاء الاصطناعي بلا حدود.",
    "GOLD PREMIUM PERKS": "مزايا العضوية الذهبية الفائقة",
    "Live Global Forex Desk": "مكتب تداول العملات العالمي المباشر",
    "Convert property deeds into Dollar, Euro, Dirham, Afghan Afghani & Turkish Lira instantly.": "تحويل فوري لقيمة العقارات إلى الدولار، اليورو، الدرهم، الأفغاني، والليرة التركية.",
    "Unlimited Active Postings": "إعلانات عقارية غير محدودة",
    "Bypass the 2-listing limitation completely. Host an endless catalog of premium cadastral items.": "تخطي حد الإعلانات تماماً وانشر دليلاً عقارياً استثنائياً.",
    "4-Engine AI Consultation Suite": "أربعة محركات ذكاء اصطناعي متخصصة",
    "Unlock expert investment ROIs, materials checkups, and area statistical breakdowns.": "احصل على استشارات استثمارية، فحص مواد البناء، وتحليلات ديموغرافية ومحلية.",
    "Gold Verified Trusted Badge": "شارة الوكيل المعتمد الذهبية",
    "Instill supreme buyer trust. Get labeled as a verified municipal broker with golden checkmarks.": "عزز ثقة المشترين واكتسب علامة التحقق الذهبية بجوار ملفك الشخصي.",
    "Advanced Export Options": "خيارات تصدير متقدمة",
    "Compile valuation portfolios into presentable client documents with customizable contact grids.": "قم بتصدير تحليلات المنطقة والأسعار بضغطة زر إلى ملفات PDF أو Excel.",
    "ACTIVATION DETAILS": "تفاصيل الفاتورة والاشتراك",
    "✉️ Broker Account Email:": "✉️ البريد الإلكتروني للحساب:",
    "💳 Select Secure Checkout Method:": "💳 اختر طريقة الدفع الآمنة:",
    "Debit Card": "بطاقة دفع بنكية (شتاب)",
    "Tether USDT": "عملة رقمية (USDT)",
    "Gold Base Subscription:": "التسعيرة الأساسية للاشتراك الذهبي:",
    "🎁 Global Site Discount:": "🎁 الخصم العام في الموقع الإلكتروني:",
    "🎫 Your Promo Code Discount:": "🎫 خصم كود الترويج الخاص بك:",
    "Net Payable Total:": "إجمالي المبلغ المستحق للدفع:",
    "🎫 Special Promo Code:": "🎫 كود خصم خاص:",
    "Verify": "تحقق",
    "💳 Destination Admin Bank Card Number:": "💳 رقم كارت البنك المستلم (الإدارة):",
    "✓ Transfer subscription fee to the admin card above and input your sender card info below.": "✓ قم بتحويل الرسوم إلى الكارت أعلاه ثم املأ بيانات المحوّل في الأسفل.",
    "👤 Your 16-Digit Sender Card Number:": "👤 رقم كارت البنك المرسل المكون من 16 رقماً:",
    "👤 Cardholder Name:": "👤 اسم صاحب الكارت المحوّل:",
    "📸 Upload Transfer Document (Receipt/Slip Photo):": "📸 رفع مستند الإيداع / صورة فیش التحويل:",
    "Document attached successfully": "تم إرفاق إيصال التحويل بنجاح",
    "Click to select or drag & drop slip file": "انقر هنا لاختيار مستند أو اسحبه إلى هنا",
    "(Allowed types: JPG, PNG, PDF)": "(الملفات المسموحة: JPG, PNG, PDF)",
    "USDT address (TRC-20):": "عنوان محفظة تتر (TRC-20):",
    "✓ Deposit USDT inside the cadastral vault and trigger approval ledger.": "✓ بعد تحويل التتر، اضغط على زر تفعيل الحساب في الأسفل.",
    "💡 Cadastral cloud profiles are compiled in local sandbox caching and dynamic system memory, instantly upgrading server responses across and updating layouts.": "💡 تعتمد خرزة الحساب الذهبي على تفعيل خوادم الذاكرة السحابية الذكية.",
    "Cancel": "إلغاء",
    "Submit & Launch Gold Pro Class": "إرسال البيانات وتفعيل الحساب الذهبي",
    "Verifying & Committing Golden Ledger...": "جاري التحقق وتسجيل اشتراكك الذهبي...",
    "🎉 Congratulations! Ariana Gold Subscription Activated!": "🎉 مبارك! تم تفعيل اشتراكك الذهبي بنجاح!",
    "Your real estate agency account is now in Gold premium status. Live world exchange rates, specialized AI engines, and limitless listings are fully unlocked.": "تم ترقية حسابك إلى الفئة الذهبية. الآن تم فتح أسعار الصرف الحية والذكاء الاصطناعي غير المحدود.",
    "Active Member Profile:": "المعرف الذهبي المعتمد:",
    "Access Level:": "فئة الاشتراك الحالية:",
    "GOLD CADASTRAL PRO": "وكيل ذهبي معتمد (GOLD PRO)",
    "Expires at:": "صلاحية الاشتراك لغاية:",
    "Excellent, Start Using Gold Features": "ممتاز، ابدأ باستخدام ميزات كاداستر الذهبية",
    "🛡️ Continuous blockchain encryption & municipal standard validation is guaranteed.": "🛡️ نضمن تشفير وحماية المعاملات وفق أعلى معايير الحماية.",
    "Install App": "تثبيت التطبيق",
    "Install Our App": "تثبيت التطبيق",
    "Install {brand} Premium App": "تثبيت تطبيق كاداستر الملكية",
    "Install our fast web-app shortcut registry. Gain instant, non-browser entry to cadastral maps and AI assistants with a dedicated application icon on your homescreen.": "قم بتثبيت تطبيق الويب السريع للوصول الفوري والمجاني إلى الخرائط ومستشاري الذكاء الاصطناعي دون الحاجة للمستعرض.",
    "Google Sandbox Frame Active": "وضع حماية جوجل المدمج نشط",
    "Direct PWA installation handles are disabled inside nested sandboxed frames due to Chrome security policies inside iframe. Press the golden button below to launch an independent browser context, open in a new tab, and install instantly.": "يتعذر التثبيت التلقائي داخل إطار الحماية الخاص بجوجل. اضغط على الزر الذهبي لفتح التطبيق في نافذة مستقلة وبدء التثبيت فوراً.",
    "Launch Standalone & Install Easily": "الفتح في نافذة مستقلة والتثبيت السهل",
    "Open this page in Safari browser, then tap the 'Share' tool at the bottom.": "افتح الصفحة بواسطة Safari ثم اضغط على أيقونة المشاركة بالأسفل.",
    "Scroll down the list and select the 'Add to Home Screen' action.": "اسحب القائمة لأسفل واختر 'أضف إلى الصفحة الرئيسية'.",
    "Click 'Add' on the upper corner of your screen to conclude setting the shortcut.": "اضغط على زر (Add) في الزاوية العلوية لتثبيت التطبيق.",
    "Click our green 'Install' header button, or expand the browser menu button (⋮).": "اضغط على زر التثبيت الأخضر بالأعلى أو افتح قائمة المزيد للمتصفح (⋮).",
    "Locate and toggle the 'Install app' or 'Add to Home screen' trigger.": "ابحث عن خيار 'تثبيت التطبيق' أو 'الاضافة لشاشة الهاتف الرسمية'.",
    "Confirm the prompt. The operating system will complete setup as a standalone tool!": "وافق على الإجراء، وسيقوم النظام بتنزيل الأيقونة الرسمية فوراً.",
    "No Desktop Shortcut on Windows 11?": "لم تظهر الأيقونة على سطح المكتب؟",
    "Windows Chrome installs PWAs quietly. If missing on desktop: open chrome://apps in Chrome, right-click 'Melkban' -> 'Create shortcut' -> check 'Desktop'. Or simply search for the app name in your Windows Start Menu.": "يقوم متصفح كروم بالتثبيت بدون إشعار. للتفعيل انتقل إلى chrome://apps وانقر باليمين لإنشاء الاختصار.",
    "Got it": "حسناً، فهمت ذلك",
    "Install Instantly": "ابدأ التثبيت الفوري",
  },
  ps: {
    "💎 Upgrade to Melkban Gold Agency Panel": "💎 د ملک‌بان زرو نمایندګۍ پینل ته لوړول",
    "Go global, access real-time forex indices & utilize unlimited AI engine configurations.": "نړیوال شئ، د اسعارو نرخونو ته په ریښتیني وخت کې لاسرسی ومومئ او د AI بې بنسټه بڼې وکاروئ.",
    "GOLD PREMIUM PERKS": "د زرو غړیتوب ځانګړي امتیازات",
    "Live Global Forex Desk": "د اسعارو ژوندی نړیوال میز",
    "Convert property deeds into Dollar, Euro, Dirham, Afghan Afghani & Turkish Lira instantly.": "د ملکیت سندونه په سمدستي ډول ډالر، یورو، درهم، افغانۍ او ترکي لیرې ته بدل کړئ.",
    "Unlimited Active Postings": "نامحدوده فعال اعلانونه",
    "Bypass the 2-listing limitation completely. Host an endless catalog of premium cadastral items.": "د ۲ اعلانونو محدودیت په بشپړ ډول له منځه یوسئ. بې حده بډایه ملکیتونه ثبت کړئ.",
    "4-Engine AI Consultation Suite": "د ۴ انجنونو لرونکی همکار AI کڅوړه",
    "Unlock expert investment ROIs, materials checkups, and area statistical breakdowns.": "د پانګونې ارزونه، د موادو چک کول، او د سیمې احصایوي معلومات پرانیزئ.",
    "Gold Verified Trusted Badge": "د تایید شوي باوري کارپوه نښان",
    "Instill supreme buyer trust. Get labeled as a verified municipal broker with golden checkmarks.": "د پیرودونکو پوره باور ترلاسه کړئ. ستاسو په پروفایل کې زرین نښان ښکاره کړئ.",
    "Advanced Export Options": "پرمختللي صادراتو اختیارونه",
    "Compile valuation portfolios into presentable client documents with customizable contact grids.": "د سیمې شننه او اسناد په اسانۍ سره PDF یا Excel ته صادر کړئ.",
    "ACTIVATION DETAILS": "د فعالولو او فکتور په اړه معلومات",
    "✉️ Broker Account Email:": "✉️ د حساب کاري بریښنالیک:",
    "💳 Select Secure Checkout Method:": "💳 د تادیې ډاډمنه طریقه وټاکئ:",
    "Debit Card": "بانکي کارت (شتاب)",
    "Tether USDT": "ډیجیټل اسعار (Tether)",
    "Gold Base Subscription:": "د زرو غړیتوب لومړنی قیمت:",
    "🎁 Global Site Discount:": "🎁 په سایټ کې عمومي تخفیف:",
    "Your Promo Code Discount:": "داخلي تخفیف:",
    "Net Payable Total:": "د تادیې وړ نهایی مقدار:",
    "🎫 Special Promo Code:": "🎫 د تخفیف ځانګړی کوډ:",
    "Verify": "تاییدول",
    "💳 Destination Admin Bank Card Number:": "💳 د مدیر د بانکي کارت ۱۶ رقمه شمیره:",
    "✓ Transfer subscription fee to the admin card above and input your sender card info below.": "✓ پورته کارت ته پیسې انتقال کړئ او د خپل کارت معلومات لاندې ولیکئ.",
    "👤 Your 16-Digit Sender Card Number:": "👤 ستاسو د ۱۶ رقمه لیږونکي کارت شمیره:",
    "👤 Cardholder Name:": "👤 د کارت د مالک نوم:",
    "📸 Upload Transfer Document (Receipt/Slip Photo):": "📸 د رسید یا واریز شوي فیش تصویر رالوډ کړئ:",
    "Document attached successfully": "رسید په بریالیتوب سره وصل شو",
    "Click to select or drag & drop slip file": "د پرانیستلو لپاره کلیک وکړئ یا فایل دلته راکاږئ",
    "(Allowed types: JPG, PNG, PDF)": "(مجاز فارمیټونه: JPG, PNG, PDF)",
    "USDT address (TRC-20):": "تتر والټ پته شبکه (TRC-20):",
    "✓ Deposit USDT inside the cadastral vault and trigger approval ledger.": "✓ د تومانونو یا تتر واریز کولو وروسته لاندې تایید تڼۍ فشار کړئ.",
    "💡 Cadastral cloud profiles are compiled in local sandbox caching and dynamic system memory, instantly upgrading server responses across and updating layouts.": "💡 د کاداستر غړیتوب د کلاوډ بې ثباته لخوا په سمدستي توګه فعالیږي.",
    "Cancel": "انصراف / لغوه",
    "Submit & Launch Gold Pro Class": "بشپړول او د زرو غړیتوب پیل کول",
    "Verifying & Committing Golden Ledger...": "د معلوماتو کتنه او ثبتول...",
    "🎉 Congratulations! Ariana Gold Subscription Activated!": "🎉 مبارک شه! ستاسو د زرو غړیتوب په بریالیتوب فعال شو!",
    "Your real estate agency account is now in Gold premium status. Live world exchange rates, specialized AI engines, and limitless listings are fully unlocked.": "ستاسو د ملکیتونو حساب متمایز شو. د اسعارو ژوندي نرخونه او د Gemini بې حده هوش درته پرانیستل شول.",
    "Active Member Profile:": "د زرو غړیتوب پیژندګلوي:",
    "Access Level:": "د اوسني لاسرسي کچه:",
    "GOLD CADASTRAL PRO": "د کاداستر رسمي زرو غړی (GOLD PRO)",
    "Expires at:": "د اعتبار تر نیټې:",
    "Excellent, Start Using Gold Features": "ډیره ښه، د زرو غړیتوب خدمتونو پیل",
    "🛡️ Continuous blockchain encryption & municipal standard validation is guaranteed.": "🛡️ د بلاک‌چین له لارې د معلوماتو خوندیتوب تضمین دی.",
    "Install App": "د اپلیکیشن نصبول",
    "Install Our App": "د اپلیکیشن یا میانبر نصب",
    "Install Ariana Rahnuma Premium App": "د آریانا رهنما اپلیکیشن د میانبر نصبول",
    "Install our fast web-app shortcut registry. Gain instant, non-browser entry to cadastral maps and AI assistants with a dedicated application icon on your homescreen.": "د کاداستر ګړندی لینک نصب کړئ ترڅو بې له انټرنیټي براوزر خلاصولو نقشو او د AI مشاور ته لاسرسی ولرئ.",
    "Google Sandbox Frame Active": "د ګوګل د امنیتي چوکاټ کنټرول فعال دی",
    "Direct PWA installation handles are disabled inside nested sandboxed frames due to Chrome security policies inside iframe. Press the golden button below to launch an independent browser context, open in a new tab, and install instantly.": "د ګوګل د چوکاټ امنیت له امله مستقیم نصب ممکن نه دی. لاندې تڼۍ واوهئ ترڅو په نوې پاڼه کې نصب کړئ.",
    "Launch Standalone & Install Easily": "په ځانګړې پاڼه کې خلاصول او اسان نصب",
    "Open this page in Safari browser, then tap the 'Share' tool at the bottom.": "دا پاڼه په Safari براوزر کې پرانیزئ او د لاندې لاس د شریکولو (Share) تڼۍ ووهئ.",
    "Scroll down the list and select the 'Add to Home Screen' action.": "په لیست کې 'Add to Home Screen' اختیار پیدا او وټاکئ.",
    "Click 'Add' on the upper corner of your screen to conclude setting the shortcut.": "د سکرین په پورته ښي کونج کې 'Add' تڼۍ ووهئ تر څو میانبر جوړ شي.",
    "Click our green 'Install' header button, or expand the browser menu button (⋮).": "په پورته برخه کې په زرغون بټن کلیک وکړی یا د براوزر مینو خلاصه کړئ.",
    "Locate and toggle the 'Install app' or 'Add to Home screen' trigger.": "د 'Install app' یا د تلیفون په سکرین د اضافه کولو اختیار وټاکئ.",
    "Confirm the prompt. The operating system will complete setup as a standalone tool!": "تایید فشار کړئ، کاریال به ستاسو د تلیفون سکرین ته په بشپړ ډول اضافه شي.",
    "No Desktop Shortcut on Windows 11?": "په وینډوز ۱۱ کې شارټ‌کټ جوړ نه شو؟",
    "Windows Chrome installs PWAs quietly. If missing on desktop: open chrome://apps in Chrome, right-click 'Melkban' -> 'Create shortcut' -> check 'Desktop'. Or simply search for the app name in your Windows Start Menu.": "د کروم براوزر په خاموشۍ نصبوي. په کروم کې chrome://apps خلاص کړئ او د شارټ‌کټ نښان فعال کړئ.",
    "Got it": "پوه شوم، بندول",
    "Install Instantly": "سمدستي نصبول"
  },
  zh: {
    "💎 Upgrade to Melkban Gold Agency Panel": "💎 升级为 Melkban 黄金代理商面板",
    "Go global, access real-time forex indices & utilize unlimited AI engine configurations.": "迈向全球，实时获取外汇指数，并使用无限的 AI 引擎配置。",
    "GOLD PREMIUM PERKS": "黄金会员专属特权",
    "Live Global Forex Desk": "实时全球外汇台",
    "Convert property deeds into Dollar, Euro, Dirham, Afghan Afghani & Turkish Lira instantly.": "立即将房产契约转换为美元、欧元、迪拉姆、阿富汗尼和土耳其里拉。",
    "Unlimited Active Postings": "无限活跃房源发布",
    "Bypass the 2-listing limitation completely. Host an endless catalog of premium cadastral items.": "完全打破 2 条房源限制。发布无限的优质地籍名录房源。",
    "4-Engine AI Consultation Suite": "四引擎 AI 智能咨询包",
    "Unlock expert investment ROIs, materials checkups, and area statistical breakdowns.": "解锁专业投资回报率分析、建材检验及区域统计数据分析。",
    "Gold Verified Trusted Badge": "金牌认证信赖徽章",
    "Instill supreme buyer trust. Get labeled as a verified municipal broker with golden checkmarks.": "树立崇高的买家信任感。贴上带金色对勾的认证市政经纪人标签。",
    "Advanced Export Options": "高级导出选项",
    "Compile valuation portfolios into presentable client documents with customizable contact grids.": "一键将估值组合导出为 PDF 或 Excel 精美报告送交客户。",
    "ACTIVATION DETAILS": "激活详情与发票",
    "✉️ Broker Account Email:": "✉️ 经纪人账号邮箱:",
    "💳 Select Secure Checkout Method:": "💳 选择安全结算方式:",
    "Debit Card": "借记卡 / 捷联卡",
    "Tether USDT": "加密货币 (USDT)",
    "Gold Base Subscription:": "基础黄金会员套餐价格:",
    "🎁 Global Site Discount:": "🎁 全球站点通用折扣:",
    "Your Promo Code Discount:": "优惠码折扣:",
    "Net Payable Total:": "最终应付总额:",
    "🎫 Special Promo Code:": "🎫 特别优惠码:",
    "Verify": "核对",
    "💳 Destination Admin Bank Card Number:": "💳 接收方管理员银行卡号:",
    "✓ Transfer subscription fee to the admin card above and input your sender card info below.": "✓ 请将订阅费转入上述管理员卡号，并在下方输入您的付款卡号信息。",
    "👤 Your 16-Digit Sender Card Number:": "👤 您的 16 位付款银行卡号:",
    "👤 Cardholder Name:": "👤 持卡人姓名:",
    "📸 Upload Transfer Document (Receipt/Slip Photo):": "📸 上传转账凭证（账单/收据照片）:",
    "Document attached successfully": "凭证上传成功",
    "Click to select or drag & drop slip file": "点击选择或拖放账单文件",
    "(Allowed types: JPG, PNG, PDF)": "(支持格式: JPG, PNG, PDF)",
    "USDT address (TRC-20):": "USDT 支付地址 (TRC-20):",
    "✓ Deposit USDT inside the cadastral vault and trigger approval ledger.": "✓ 存入 USDT 到上述地籍金库后，点击下方按钮完成最终认证。",
    "💡 Cadastral cloud profiles are compiled in local sandbox caching and dynamic system memory, instantly upgrading server responses across and updating layouts.": "💡 黄金地籍配置将通过云端分布式计算在所有系统中同步激活并升级您的账户权限。",
    "Cancel": "取消",
    "Submit & Launch Gold Pro Class": "提交并开启 Gold Pro 会员",
    "Verifying & Committing Golden Ledger...": "黄金账簿验证中...",
    "🎉 Congratulations! Ariana Gold Subscription Activated!": "🎉 恭喜！Ariana 黄金会员订阅已激活！",
    "Your real estate agency account is now in Gold premium status. Live world exchange rates, specialized AI engines, and limitless listings are fully unlocked.": "您的经纪人账户已升级为金牌状态。实时外汇换算、4款 AI 工具及无限房源发布功能已开启。",
    "Active Member Profile:": "黄金会员账号ID:",
    "Access Level:": "当前会员等级:",
    "GOLD CADASTRAL PRO": "黄金地籍高级会员 (GOLD PRO)",
    "Expires at:": "到期时间:",
    "Excellent, Start Using Gold Features": "太棒了，开启黄金特色功能",
    "🛡️ Continuous blockchain encryption & municipal standard validation is guaranteed.": "🛡️ 交易受到不间断的区块链加密和官方地籍标准保护。",
    "Install App": "安装应用",
    "Install Our App": "安装快捷应用",
    "Install Ariana Rahnuma Premium App": "安装 Ariana Rahnuma 快捷应用",
    "Install our fast web-app shortcut registry. Gain instant, non-browser entry to cadastral maps and AI assistants with a dedicated application icon on your homescreen.": "安装极速 Web App 快捷入口。无需打开浏览器，即可直接从主屏幕图标打开地籍图和 AI 智能顾问。",
    "Google Sandbox Frame Active": "Google 沙盒安全模式已启用",
    "Direct PWA installation handles are disabled inside nested sandboxed frames due to Chrome security policies inside iframe. Press the golden button below to launch an independent browser context, open in a new tab, and install instantly.": "受浏览器沙盒政策限制，目前无法直接安装。请点击下方金色按钮在独立窗口中打开并安装。",
    "Launch Standalone & Install Easily": "一键独立窗口启动并快速安装",
    "Open this page in Safari browser, then tap the 'Share' tool at the bottom.": "在 Safari 浏览器中打开此页面，然后点击底部圆圈分享按钮。",
    "Scroll down the list and select the 'Add to Home Screen' action.": "在弹出菜单中，选择“添加到主屏幕 (Add to Home Screen)”。",
    "Click 'Add' on the upper corner of your screen to conclude setting the shortcut.": "点击屏幕右上角的“添加”，完成快捷图标的创建。",
    "Click our green 'Install' header button, or expand the browser menu button (⋮).": "点击顶部的绿色‘安装’按钮，或展开浏览器菜单 (⋮)。",
    "Locate and toggle the 'Install app' or 'Add to Home screen' trigger.": "找到并选择“安装应用”或“添加到主屏幕”选项。",
    "Confirm the prompt. The operating system will complete setup as a standalone tool!": "确认弹出提示。系统将把应用添加到桌面，作为一个独立的程序运行！",
    "No Desktop Shortcut on Windows 11?": "在桌面找不到快捷方式？",
    "Windows Chrome installs PWAs quietly. If missing on desktop: open chrome://apps in Chrome, right-click 'Melkban' -> 'Create shortcut' -> check 'Desktop'. Or simply search for the app name in your Windows Start Menu.": "Chrome 浏览器通常会静默保存应用。若缺失，请在 Chrome 打开 chrome://apps 创建桌面快捷方式。",
    "Got it": "明白了，关闭引导",
    "Install Instantly": "立即开始安装"
  },
  sg: {
    "💎 Upgrade to Melkban Gold Agency Panel": "💎 Upgrade to Melkban Gold Agency Panel / 升级黄金会员",
    "Go global, access real-time forex indices & utilize unlimited AI engine configurations.": "Go global, access real-time forex indices & utilize unlimited AI engine configurations / 实时精算全球外汇与AI引擎配置",
    "GOLD PREMIUM PERKS": "GOLD PREMIUM PERKS / 黄金会员特权",
    "Live Global Forex Desk": "Live Global Forex Desk / 实时全球外汇台",
    "Convert property deeds into Dollar, Euro, Dirham, Afghan Afghani & Turkish Lira instantly.": "Convert property deeds into Dollar, Euro, Dirham, Afghan Afghani & Turkish Lira instantly / 立即外汇换算房产契约。",
    "Unlimited Active Postings": "Unlimited Active Postings / 无限活跃房源发布",
    "Bypass the 2-listing limitation completely. Host an endless catalog of premium cadastral items.": "Bypass the 2-listing limitation completely / 突破双条房源发布门槛。",
    "4-Engine AI Consultation Suite": "4-Engine AI Consultation Suite / 四大 AI 决策引擎",
    "Unlock expert investment ROIs, materials checkups, and area statistical breakdowns.": "Unlock expert investment ROIs, materials checkups, and area statistical breakdowns / 智能诊断建材、回报率和趋势分析。",
    "Gold Verified Trusted Badge": "Gold Verified Trusted Badge / 金牌信用认证",
    "Instill supreme buyer trust. Get labeled as a verified municipal broker with golden checkmarks.": "Instill supreme buyer trust / 树立最高信赖，获得金勋章标记。",
    "Advanced Export Options": "Advanced Export Options / 高级数据导出",
    "Compile valuation portfolios into presentable client documents with customizable contact grids.": "Compile valuation portfolios into PDF/Excel documents / 导出精细估算及区域趋势报表。",
    "ACTIVATION DETAILS": "ACTIVATION DETAILS / 激活发票信息",
    "✉️ Broker Account Email:": "✉️ Broker Account Email / 经纪人账号邮箱:",
    "💳 Select Secure Checkout Method:": "💳 Select Checkout Method / 选择支付方案:",
    "Debit Card": "Debit Card / 借记付款卡",
    "Tether USDT": "Tether USDT / 加密货币支付",
    "Gold Base Subscription:": "Gold Base Subscription / 基础均价费率:",
    "🎁 Global Site Discount:": "🎁 Global Site Discount / 全球专属折扣:",
    "Your Promo Code Discount:": "Promo Discount / 优惠折扣:",
    "Net Payable Total:": "Net Payable Total / 最终应付总额:",
    "🎫 Special Promo Code:": "🎫 Special Promo Code / 特别优惠码:",
    "Verify": "Verify / 验证代码",
    "💳 Destination Admin Bank Card Number:": "💳 Admin Bank Card / 管理员收款卡号:",
    "✓ Transfer subscription fee to the admin card above and input your sender card info below.": "✓ Transfer subscription fee to the admin card / 请将订阅费汇入上述银行卡号并登记付款证明。",
    "Your 16-Digit Sender Card Number:": "Sender Card Number / 付款卡号:",
    "Cardholder Name:": "Cardholder Name / 持卡人姓名:",
    "📸 Upload Transfer Document (Receipt/Slip Photo):": "📸 Upload Receipt / 上传转账汇款凭证:",
    "Document attached successfully": "Document attached successfully / 证件成功上传",
    "Click to select or drag & drop slip file": "Click to select or drag & drop / 点击或拖拽凭证文件",
    "(Allowed types: JPG, PNG, PDF)": "(Allowed types: JPG, PNG, PDF)",
    "USDT address (TRC-20):": "USDT address (TRC-20) / 收款地址:",
    "✓ Deposit USDT inside the cadastral vault and trigger approval ledger.": "✓ Deposit USDT and trigger approval ledger / 存入 USDT 汇款后点击下方激活手续。",
    "💡 Cadastral cloud profiles are compiled in local sandbox caching and dynamic system memory, instantly upgrading server responses across and updating layouts.": "💡 Centralized cloud verification upgrades your account instantly.",
    "Cancel": "Cancel / 取消",
    "Submit & Launch Gold Pro Class": "Submit & Launch Gold Pro Class / 立即激活黄金会员",
    "Verifying & Committing Golden Ledger...": "Verifying & Committing Golden Ledger... / 验证写入中...",
    "🎉 Congratulations! Ariana Gold Subscription Activated!": "🎉 Congratulations! Gold Subscription Activated! / 恭喜，黄金会员已成功激活！",
    "Your real estate agency account is now in Gold premium status. Live world exchange rates, specialized AI engines, and limitless listings are fully unlocked.": "Your account is in Gold premium status / 会员等级已升温至 Golden，外汇和AI功能均已解锁。",
    "Active Member Profile:": "Active Member Profile / 用户邮箱:",
    "Access Level:": "Access Level / 当前会员等级:",
    "GOLD CADASTRAL PRO": "GOLD CADASTRAL PRO / 黄金正式会员(PRO)",
    "Expires at:": "Expires at / 有效期截止:",
    "Excellent, Start Using Gold Features": "Excellent, Start Using Gold Features / 太棒了，开始使用黄金服务",
    "🛡️ Continuous blockchain encryption & municipal standard validation is guaranteed.": "🛡️ Secured by blockchain encryption and state cadastral registry validation.",
    "Install App": "Install App / 安装软件",
    "Install Our App": "Install Our App / 安装小程序",
    "Install Ariana Rahnuma Premium App": "Install Ariana Rahnuma Premium App / 安装官方独立客户端",
    "Install our fast web-app shortcut registry. Gain instant, non-browser entry to cadastral maps and AI assistants with a dedicated application icon on your homescreen.": "Install our fast web-app shortcut. Gain instant, non-browser entry to maps & AI / 安装小程序，即开即用地籍地图及 AI 客服。",
    "Google Sandbox Frame Active": "Google Sandbox Frame Active / 安全沙箱环境检测正常",
    "Direct PWA installation handles are disabled inside nested sandboxed frames due to Chrome security policies inside iframe. Press the golden button below to launch an independent browser context, open in a new tab, and install instantly.": "Direct PWA install disabled inside frame. Launch standalone to install instantly / 检测到沙盒容器，请点击金色按钮跳出环境即可无缝下载。",
    "Launch Standalone & Install Easily": "Launch Standalone & Install Easily / 独立窗口快速运行安装",
    "Open this page in Safari browser, then tap the 'Share' tool at the bottom.": "Open in Safari browser, tap the 'Share' icon / 请在 Safari 浏览器中打开，点击底部分享栏。",
    "Scroll down the list and select the 'Add to Home Screen' action.": "Scroll down, select 'Add to Home Screen' / 向下滑动选择“添加到主屏幕”。",
    "Click 'Add' on the upper corner of your screen to conclude setting the shortcut.": "Click 'Add' on upper corner / 在控制面板右上角选择“添加”即可。",
    "Click our green 'Install' header button, or expand the browser menu button (⋮).": "Click our green 'Install' button, or expand browser menu (⋮) / 点击上方绿色‘安装’按钮或浏览器菜单。",
    "Locate and toggle the 'Install app' or 'Add to Home screen' trigger.": "Locate and toggle 'Install app' or 'Add to Home screen' / 选择“安装应用”或“添加到主屏幕”。",
    "Confirm the prompt. The operating system will complete setup as a standalone tool!": "Confirm prompt. System will install standalone application / 确认安装意图，系统将自动固定到工作区桌面上！",
    "No Desktop Shortcut on Windows 11?": "No Desktop Shortcut on Windows 11? / 桌面缺少快捷方式？",
    "Windows Chrome installs PWAs quietly. If missing on desktop: open chrome://apps in Chrome, right-click 'Melkban' -> 'Create shortcut' -> check 'Desktop'. Or simply search for the app name in your Windows Start Menu.": "Open chrome://apps in Chrome, create shortcut / 请在 Chrome 打开 chrome://apps 菜单建立桌面快捷入口。",
    "Got it": "Got it / 我知道了，关闭",
    "Install Instantly": "Install Instantly / 智能一键快速下载"
  },
  ur: {
    "💎 Upgrade to Melkban Gold Agency Panel": "💎 ملک‌بان گولڈ ایجنسی پینل میں اپ گریڈ کریں",
    "Go global, access real-time forex indices & utilize unlimited AI engine configurations.": "عالمی بنیں، اسعار کے تبادلے کے انڈیکسز تک رسائی حاصل کریں اور لامحدود AI ٹو لز استعمال کریں۔",
    "GOLD PREMIUM PERKS": "گولڈ پریمیم کی خصوصیات",
    "Live Global Forex Desk": "براہ راست عالمی فاریکس قیمتیں",
    "Convert property deeds into Dollar, Euro, Dirham, Afghan Afghani & Turkish Lira instantly.": "جائیداد کی فیس فوری طور پر ڈالر، یورو، درہم، افغانی اور ترک لیرہ میں تبدیل کریں۔",
    "Unlimited Active Postings": "لامحدود صیغہ جات کی آویزانی",
    "Bypass the 2-listing limitation completely. Host an endless catalog of premium cadastral items.": "2 اشتہارات کی حد کو مکمل طور پر بائی پاس کریں۔ لامحدود پریمیم جائیدادیں شامل کریں۔",
    "4-Engine AI Consultation Suite": "4 ماڈلز والا خصوصی AI مشاور",
    "Unlock expert investment ROIs, materials checkups, and area statistical breakdowns.": "انویسٹمنٹ ریٹرن تجزیہ، عمارتی سامان کی مینوفیکچرنگ اور علاقائی اعداد و شمار انلاک کریں۔",
    "Gold Verified Trusted Badge": "گولڈ تصدیق شدہ ٹرسٹ کارڈ",
    "Instill supreme buyer trust. Get labeled as a verified municipal broker with golden checkmarks.": "خریداروں کا مکمل اعتماد حاصل کریں۔ سنہری نشان کے ساتھ تصدیق شدہ بروکر بنیں۔",
    "Advanced Export Options": "پریمیم ایکسپورٹ آپشنز",
    "Compile valuation portfolios into presentable client documents with customizable contact grids.": "علاقائی تجزیہ رپورٹس ایک کلک میں پی ڈی ایف یا ایکسل فائلز میں ڈاؤن لوڈ کریں۔",
    "ACTIVATION DETAILS": "ایکٹیویشن کی تفصیلات اور بلنگ",
    "✉️ Broker Account Email:": "✉️ ایجنسی اکاؤنٹ کا ای میل:",
    "💳 Select Secure Checkout Method:": "💳 محفوظ ادائیگی کا طریقہ منتخب کریں:",
    "Debit Card": "بینک ڈیبٹ کارڈ (شتاب)",
    "Tether USDT": "ڈیجیٹل کرنسی (USDT)",
    "Gold Base Subscription:": "بنیادی گولڈ سبسکرپشن چارجز:",
    "🎁 Global Site Discount:": "🎁 عام ڈسکاؤنٹ ملکی لیول پر:",
    "Your Promo Code Discount:": "پرومو ڈسکاؤنٹ:",
    "Net Payable Total:": "حتمی واجب الادا رقم:",
    "🎫 Special Promo Code:": "🎫 خصوصی پرومو کوڈ:",
    "Verify": "تصدیق کریں",
    "💳 Destination Admin Bank Card Number:": "💳 موصول کنندہ ایڈمن کا شتاب بینک ورچوئل کارڈ نمبر:",
    "✓ Transfer subscription fee to the admin card above and input your sender card info below.": "✓ اوپر دیے گئے کارڈ نمبر پر سبسکرپشن فیس بھیجیں اور نیچے اپنے کارڈ کی تفصیلات درج کریں۔",
    "👤 Your 16-Digit Sender Card Number:": "👤 آپ کا 16 ہندسی کارڈ نمبر:",
    "👤 Cardholder Name:": "👤 کارڈ ہولڈر کا نام:",
    "📸 Upload Transfer Document (Receipt/Slip Photo):": "📸 ادائیگی کی رسید/اسکرین شاٹ لوڈ کریں:",
    "Document attached successfully": "ادائیگی کی رسید کامیابی سے منسلک ہو گئی",
    "Click to select or drag & drop slip file": "اٹیچ کرنے کے لیے کلک کریں یا فائل یہاں گھسیٹیں",
    "(Allowed types: JPG, PNG, PDF)": "(فائل فارمیٹ: JPG، PNG، PDF)",
    "USDT address (TRC-20):": "تتھر والٹ ایڈریس (TRC-20):",
    "✓ Deposit USDT inside the cadastral vault and trigger approval ledger.": "✓ والٹ میں تتھر جمع کرانے کے بعد، نیچے تصدیق کی تندہی دبا دیں۔",
    "💡 Cadastral cloud profiles are compiled in local sandbox caching and dynamic system memory, instantly upgrading server responses across and updating layouts.": "💡 آپ کا گولڈ کارڈ کلاؤډ انٹیگریشن کے ذریعے فوری طور پر ایکٹیویٹ ہو جائے گا۔",
    "Cancel": "انصراف / کینسل",
    "Submit & Launch Gold Pro Class": "جمع کرائیں اور گولڈ پریمیم پر جائیں",
    "Verifying & Committing Golden Ledger...": "تفصیلات کی جانچ پڑتال جاری ہے...",
    "🎉 Congratulations! Ariana Gold Subscription Activated!": "🎉 مبارک ہو! آپ کی گولڈ سبسکرپشن کامیابی سے فعال ہو گئی ہے!",
    "Your real estate agency account is now in Gold premium status. Live world exchange rates, specialized AI engines, and limitless listings are fully unlocked.": "آپ کا ایجنسی اکاؤنٹ اب گولڈ پریمیم ہے۔ لائیو فاریکس ریٹس، 4 AI سسٹمز اور لامحدود لسٹنگز اب فعال ہے۔",
    "Active Member Profile:": "گولڈ ہولڈر پروفائل ای میل:",
    "Access Level:": "عضویت کا درجہ:",
    "GOLD CADASTRAL PRO": "گولڈ آفیشل ممبر (GOLD PRO)",
    "Expires at:": "تاریخ ختم ہونے کی مدت:",
    "Excellent, Start Using Gold Features": "بہت عمدہ، گولڈ فیچرز استعمال کرنا شروع کریں",
    "🛡️ Continuous blockchain encryption & municipal standard validation is guaranteed.": "🛡️ بلاتعطل بلاک چین پروٹیکشن اور آفیشل تحفظ کی ضمانت ہے۔",
    "Install App": "ایپ انسٹال کریں",
    "Install Our App": "ہوم اسکرین ایپ انسٹال کریں",
    "Install Ariana Rahnuma Premium App": "آریانا رهنما پریمیم ایپ انسٹال کریں",
    "Install our fast web-app shortcut registry. Gain instant, non-browser entry to cadastral maps and AI assistants with a dedicated application icon on your homescreen.": "ہماری تیز رفتار ویب ایپ انسٹال کریں اور براؤزر کے بغیر براہِ راست نقشہ جات اور پیش رفت میں مدد پائیں۔",
    "Google Sandbox Frame Active": "گوگل سینڈ بکس سیکیورٹی موڈ فعال ہے",
    "Direct PWA installation handles are disabled inside nested sandboxed frames due to Chrome security policies inside iframe. Press the golden button below to launch an independent browser context, open in a new tab, and install instantly.": "گوگل کی سیکیورٹی پالیسی کی وجہ سے بلا واسطہ انسٹال ہونا مقفل ہے۔ ذیلی پینل میں انسٹال کرنے کے لیے نیچے والا بٹن دبائیں۔",
    "Launch Standalone & Install Easily": "نئی ونڈو میں ایپ کھولیں اور آسانی سے انسٹال کریں",
    "Open this page in Safari browser, then tap the 'Share' tool at the bottom.": "صفحہ کو سفاری (Safari) میں کھولیں اور نیچے شیئر کے آئیکن پر کلک کریں۔",
    "Scroll down the list and select the 'Add to Home Screen' action.": "کھلنے والے مینیو میں 'Add to Home Screen' تلاش کر کے منتخب کریں۔",
    "Click 'Add' on the upper corner of your screen to conclude setting the shortcut.": "شارٹ کٹ بنانے کے لیے بالائی دائیں کونے پر 'Add' پر کلک کریں۔",
    "Click our green 'Install' header button, or expand the browser menu button (⋮).": "اوپری سبز انسٹال بٹن دبائیں یا تین نقطوں (⋮) والے مینیو کو کھولیں۔",
    "Locate and toggle the 'Install app' or 'Add to Home screen' trigger.": "'Install app' یا ہوم اسکرین پر شامل کرنے کا آپشن منتخب کریں۔",
    "Confirm the prompt. The operating system will complete setup as a standalone tool!": "پراپمٹ کی تصدیق کریں۔ سسٹم اب ڈیسک ٹاپ آئیکن کے طور پر شامل کر دے گا!",
    "No Desktop Shortcut on Windows 11?": "ڈیسک ٹاپ پر شارٹ کٹ ظاہر نہیں ہوا؟",
    "Windows Chrome installs PWAs quietly. If missing on desktop: open chrome://apps in Chrome, right-click 'Melkban' -> 'Create shortcut' -> check 'Desktop'. Or simply search for the app name in your Windows Start Menu.": "کروم ایپ کو خاموشی سے انسٹال کرتا ہے۔ chrome://apps پر جا کر شارٹ کٹ ڈیسک ٹاپ کے لیے انیبل کریں۔",
    "Got it": "سمجھ گیا، بند کریں",
    "Install Instantly": "فوری انسٹالیشن"
  },
  hi: {
    "💎 Upgrade to Melkban Gold Agency Panel": "💎 मल्कबान गोल्ड एजेंसी पैनल में अपग्रेड करें",
    "Go global, access real-time forex indices & utilize unlimited AI engine configurations.": "वैश्विक बनें, वास्तविक समय विदेशी मुद्रा सूचकांक प्राप्त करें और असीमित एआई टूल्स का उपयोग करें।",
    "GOLD PREMIUM PERKS": "गोल्ड प्रीमियम विशेषाधिकार",
    "Live Global Forex Desk": "लाइव ग्लोबल फॉरेक्स विनिमय दर",
    "Convert property deeds into Dollar, Euro, Dirham, Afghan Afghani & Turkish Lira instantly.": "संपत्ति के दस्तावेजों को तुरंत डॉलर, यूरो, दिरहम और अफगानी में बदलें।",
    "Unlimited Active Postings": "असीमित सक्रिय लिस्टिंग",
    "Bypass the 2-listing limitation completely. Host an endless catalog of premium cadastral items.": "2 विज्ञापनों की सीमा को पूरी तरह से हटा दें। असीमित प्रीमियम संपत्तियां जोड़ें।",
    "4-Engine AI Consultation Suite": "4-इंजन विशेषज्ञ एआई सहायता",
    "Unlock expert investment ROIs, materials checkups, and area statistical breakdowns.": "निवेश पर रिटर्न विश्लेषण, भवन निर्माण सामग्री सत्यापन और स्थानीय आंकड़ों की जांच खोलें।",
    "Gold Verified Trusted Badge": "गोल्ड सत्यापित विश्वसनीय ब्रोकर बैज",
    "Instill supreme buyer trust. Get labeled as a verified municipal broker with golden checkmarks.": "खरीदारों का अत्यधिक विश्वास अर्जित करें। अपने प्रोफाइल पर गोल्डन बैज प्राप्त करें।",
    "Advanced Export Options": "उन्नत रिपोर्ट निर्यात विकल्प",
    "Compile valuation portfolios into presentable client documents with customizable contact grids.": "क्षेत्रीय विश्लेषण रिपोर्ट को एक क्लिक में पीडीएफ या एक्सेल में सहेजें।",
    "ACTIVATION DETAILS": "सक्रियण विवरण और बिलिंग जानकारी",
    "✉️ Broker Account Email:": "✉️ ब्रोकर खाता ईमेल आईडी:",
    "💳 Select Secure Checkout Method:": "💳 सुरक्षित भुगतान प्रक्रिया का चयन करें:",
    "Debit Card": "डेबिट कार्ड (शताब)",
    "Tether USDT": "डिजिटल मुद्रा (Tether USDT)",
    "Gold Base Subscription:": "मूल सदस्यता शुल्क:",
    "🎁 Global Site Discount:": "🎁 वैश्विक साइट डिस्काउंट प्रतिशत:",
    "Your Promo Code Discount:": "विशिष्ट कूपन छूट:",
    "Net Payable Total:": "पूरी अंतिम देय राशि:",
    "🎫 Special Promo Code:": "🎫 विशेष प्रचार कोड:",
    "Verify": "सत्यापन करें",
    "💳 Destination Admin Bank Card Number:": "💳 प्राप्तकर्ता व्यवस्थापक का 16-अंकीय कार्ड नंबर:",
    "✓ Transfer subscription fee to the admin card above and input your sender card info below.": "✓ ऊपर दिए गए व्यवस्थापक खाते में शुल्क भेजें और अपना विवरण दर्ज करें।",
    "👤 Your 16-Digit Sender Card Number:": "👤 आपका 16-अंकीय भेजने वाला कार्ड नंबर:",
    "👤 Cardholder Name:": "👤 कार्डधारक का पूरा नाम:",
    "📸 Upload Transfer Document (Receipt/Slip Photo):": "📸 भुगतान रसीद की फोटो अपलोड करें:",
    "Document attached successfully": "दस्तावेज़ सफलतापूर्वक संलग्न किया गया",
    "Click to select or drag & drop slip file": "चयन करने के लिए क्लिक करें या फ़ाइल यहाँ खींचें",
    "(Allowed types: JPG, PNG, PDF)": "(अनुमत प्रारूप: JPG, PNG, PDF)",
    "USDT address (TRC-20):": "यूएसडीटी वॉलेट पता (TRC-20):",
    "✓ Deposit USDT inside the cadastral vault and trigger approval ledger.": "✓ भुगतान जमा करने के बाद नीचे पुष्टि देने वाला बटन दबाएं।",
    "💡 Cadastral cloud profiles are compiled in local sandbox caching and dynamic system memory, instantly upgrading server responses across and updating layouts.": "💡 आपका गोल्ड प्रोफ़ाइल क्लाउड बहीखाता द्वारा तुरंत सक्रिय कर दिया जाएगा।",
    "Cancel": "रद्द करें",
    "Submit & Launch Gold Pro Class": "जमा करें और गोल्ड क्लास शुरू करें",
    "Verifying & Committing Golden Ledger...": "पुष्टि और प्रक्रिया जारी है...",
    "🎉 Congratulations! Ariana Gold Subscription Activated!": "🎉 बधाई हो! आपकी गोल्ड सदस्यता सफलतापूर्वक चालू हो गई है!",
    "Your real estate agency account is now in Gold premium status. Live world exchange rates, specialized AI engines, and limitless listings are fully unlocked.": "आपका खाता अब गोल्ड प्रीमियम स्तर पर है। लाइव फॉरेक्स, 4 एआई टूल्स सक्रिय कर दिए गए हैं।",
    "Active Member Profile:": "सक्रिय सदस्य ईमेल प्रोफाइल:",
    "Access Level:": "सदस्यता की श्रेणी:",
    "GOLD CADASTRAL PRO": "गोल्ड सरकारी प्रो स्तर (GOLD PRO)",
    "Expires at:": "सदस्यता की समाप्ति तिथि:",
    "Excellent, Start Using Gold Features": "शानदार, गोल्ड सुविधाओं का उपयोग शुरू करें",
    "🛡️ Continuous blockchain encryption & municipal standard validation is guaranteed.": "🛡️ लगातार ब्लॉकचेन एन्क्रिप्शन और आधिकारिक मान्यता की गारंटी है।",
    "Install App": "ऐप इंस्टॉल करें",
    "Install Our App": "होमस्क्रीन ऐप इंस्टॉल करें",
    "Install Ariana Rahnuma Premium App": "आरीयाना रहनुमा ऐप इंस्टॉल करें",
    "Install our fast web-app shortcut registry. Gain instant, non-browser entry to cadastral maps and AI assistants with a dedicated application icon on your homescreen.": "हमारा तेज़ ऐप इंस्टॉल करें और बिना ब्राउज़र के भू-नक्शों और एआई का त्वरित लाभ उठाएं।",
    "Google Sandbox Frame Active": "गूगल सैंडबॉक्स मोड सक्रिय है",
    "Direct PWA installation handles are disabled inside nested sandboxed frames due to Chrome security policies inside iframe. Press the golden button below to launch an independent browser context, open in a new tab, and install instantly.": "गूगल सुरक्षा नीति के कारण यहाँ सीधे इंस्टॉल करना प्रतिबंधित है। नई विंडो के लिए नीचे दबाएं।",
    "Launch Standalone & Install Easily": "स्वतंत्र नई विंडो में खोलकर इंस्टॉल करें",
    "Open this page in Safari browser, then tap the 'Share' tool at the bottom.": "सफ़ारी (Safari) ब्राउज़र में खोलें, नीचे 'शेयर' पर टैप करें।",
    "Scroll down the list and select the 'Add to Home Screen' action.": "खुलने वाली सूची में 'Add to Home Screen' का चयन करें।",
    "Click 'Add' on the upper corner of your screen to conclude setting the shortcut.": "शॉर्टकट जोड़ने के लिए ऊपर दाईं ओर 'Add' पर क्लिक करें।",
    "Click our green 'Install' header button, or expand the browser menu button (⋮).": "ऊपरी हरे रंग वाले ऐप डाउनलोड बटन को दबाएं या ब्राउज़र मेनू का इस्तेमाल करें।",
    "Locate and toggle the 'Install app' or 'Add to Home screen' trigger.": "सूची में 'Install app' या स्क्रीन पर सहेजने का चयन करें।",
    "Confirm the prompt. The operating system will complete setup as a standalone tool!": "निर्देशों की पुष्टि करें, ऑपरेटिंग सिस्टम स्वचालित रूप से इसे होमस्क्रीन में जोड़ देगा!",
    "No Desktop Shortcut on Windows 11?": "विंडोज 11 डेस्कटॉप पर शॉर्टकट नहीं मिला?",
    "Windows Chrome installs PWAs quietly. If missing on desktop: open chrome://apps in Chrome, right-click 'Melkban' -> 'Create shortcut' -> check 'Desktop'. Or simply search for the app name in your Windows Start Menu.": "क्रोम पृष्ठभूमि में सहेजता है। chrome://apps खोलें और शॉर्टकट डेस्कटॉप के लिए सक्रिय करें।",
    "Got it": "समझ गया, बंद करें",
    "Install Instantly": "तुरंत ऐप इंस्टॉल करें"
  },
  ja: {
    "💎 Upgrade to Melkban Gold Agency Panel": "💎 Melkbanゴールド代理店パネルにアップグレード",
    "Go global, access real-time forex indices & utilize unlimited AI engine configurations.": "グローバル市場に対応し、リアルタイム為替情報を取得、無制限のAI機能統合を展開しましょう。",
    "GOLD PREMIUM PERKS": "ゴールドプレミアム会員の特典",
    "Live Global Forex Desk": "世界のリアルタイム為替デスク",
    "Convert property deeds into Dollar, Euro, Dirham, Afghan Afghani & Turkish Lira instantly.": "登記事項を自動でドル、ユーロ、ディルハム、アフガニに超速変換表示します。",
    "Unlimited Active Postings": "公開投稿数の制限撤廃",
    "Bypass the 2-listing limitation completely. Host an endless catalog of premium cadastral items.": "最大2件のシステム投稿制約から完全に開放されます。無制限に公開可能。",
    "4-Engine AI Consultation Suite": "4系統の特化型AIアシスタント",
    "Unlock expert investment ROIs, materials checkups, and area statistical breakdowns.": "投資採算 CAGR 予測、材料監査、エリア経済などGemini AIが完全解説します。",
    "Gold Verified Trusted Badge": "「公認・信頼された仲介業者」のゴールド認定マーク",
    "Instill supreme buyer trust. Get labeled as a verified municipal broker with golden checkmarks.": "プロフィールの横に黄金のバッジを表示し、落札確率を約140%向上させます。",
    "Advanced Export Options": "高度なデータエクスポート",
    "Compile valuation portfolios into presentable client documents with customizable contact grids.": "エリア査定や詳細資料を、ワンクリックで印刷用PDFやExcelに書き出します。",
    "ACTIVATION DETAILS": "アクティベーションとご請求の明細",
    "✉️ Broker Account Email:": "✉️ 登録代理店用の確認メール:",
    "💳 Select Secure Checkout Method:": "💳 ご決済オプションのご選択:",
    "Debit Card": "デビット決済 (Shetabネット)",
    "Tether USDT": "暗号資産仮想通貨 (USDT)",
    "Gold Base Subscription:": "月額の基本メンバーシップ費:",
    "🎁 Global Site Discount:": "🎁 プラットフォーム全体限定優待割引:",
    "Your Promo Code Discount:": "特定プロモコード割引:",
    "Net Payable Total:": "最終お支払い確定金額:",
    "🎫 Special Promo Code:": "🎫 特別割引コード (プロモコード):",
    "Verify": "適用する",
    "💳 Destination Admin Bank Card Number:": "💳 管理者宛て決済用の受領口座（16桁）:",
    "✓ Transfer subscription fee to the admin card above and input your sender card info below.": "✓ 決済費を上記の番号へ送金完了後、送信に用いた詳細を以下に記入してください。",
    "👤 Your 16-Digit Sender Card Number:": "👤 送金元のお支払いカード番号（16桁）:",
    "👤 Cardholder Name:": "👤 送金者の本名名義:",
    "📸 Upload Transfer Document (Receipt/Slip Photo):": "📸 振込完了を証明する決済明細（レシート・画像の添付）:",
    "Document attached successfully": "領収書類の添付が正常に処理されました",
    "Click to select or drag & drop slip file": "こちらをクリックして領収を添付、またはドロップ",
    "(Allowed types: JPG, PNG, PDF)": "(サポートされているフォーマット: JPG、PNG、PDF)",
    "USDT address (TRC-20):": "テザー受信受領アドレス (TRC-20):",
    "✓ Deposit USDT inside the cadastral vault and trigger approval ledger.": "✓ 送信完了を確認後、ページ下部のアクティブ化ボタンを押下してください。",
    "💡 Cadastral cloud profiles are compiled in local sandbox caching and dynamic system memory, instantly upgrading server responses across and updating layouts.": "💡 クラウドの認証システムが作動し、お客様のアカウントが即時でアップグレードされます。",
    "Cancel": "キャンセルして戻る",
    "Submit & Launch Gold Pro Class": "申し込みを確定してゴールド版を開始",
    "Verifying & Committing Golden Ledger...": "申請情報を照合・台帳に記帳しています...",
    "🎉 Congratulations! Ariana Gold Subscription Activated!": "🎉 ゴールドメンバーシップの有効化に成功しました！",
    "Your real estate agency account is now in Gold premium status. Live world exchange rates, specialized AI engines, and limitless listings are fully unlocked.": "アカウントがゴールドのプロ会員に移行しました。無制限登録、為替相場、4種のAI機能が完了しました。",
    "Active Member Profile:": "アクティブ化した対象のご登録メール:",
    "Access Level:": "現在のアカウント階級:",
    "GOLD CADASTRAL PRO": "ゴールド認定・プロメンバー(GOLD PRO)",
    "Expires at:": "正規資格の有効期間:",
    "Excellent, Start Using Gold Features": "早速ゴールド仕様でサービスを開始",
    "🛡️ Continuous blockchain encryption & municipal standard validation is guaranteed.": "🛡️ 処理はブロックチェーン暗号技術により高度に保護されています。",
    "Install App": "アプリのインストール",
    "Install Our App": "ホーム画面にショートカットを作成",
    "Install Ariana Rahnuma Premium App": "アリアナ地籍アプリをインストール",
    "Install our fast web-app shortcut registry. Gain instant, non-browser entry to cadastral maps and AI assistants with a dedicated application icon on your homescreen.": "軽量な拡張アプリをホーム画面に保存することで、ブラウザを使わずに直接マップやAIへの即時接続を確保できます。",
    "Google Sandbox Frame Active": "Googleの隔離セーフティ環境が作動中",
    "Direct PWA installation handles are disabled inside nested sandboxed frames due to Chrome security policies inside iframe. Press the golden button below to launch an independent browser context, open in a new tab, and install instantly.": "セキュリティ枠制限により直接の登録が保護されています。下の金色のボタンを押して別ウィンドウで開いて完了してください。",
    "Launch Standalone & Install Easily": "別画面からアプリとして直ちに追加する",
    "Open this page in Safari browser, then tap the 'Share' tool at the bottom.": "Safariでお開き頂き、一番下にある「共有（四角に矢印）」アイコンを選びます。",
    "Scroll down the list and select the 'Add to Home Screen' action.": "開いたリストより「ホーム画面に追加 (Add to Home Screen)」を選択します。",
    "Click 'Add' on the upper corner of your screen to conclude setting the shortcut.": "右上隅の「追加」ボタンを押下すればホーム画面化が完了となります。",
    "Click our green 'Install' header button, or expand the browser menu button (⋮).": "上部の緑色の「追加」ボタンをタップするか、ブラウザ右上のメニュー「⋮」を展開します。",
    "Locate and toggle the 'Install app' or 'Add to Home screen' trigger.": "「アプリをインストール」または「ホーム画面に追加」を実行します。",
    "Confirm the prompt. The operating system will complete setup as a standalone tool!": "ポップアップを確認、許可。オペレーティングシステムに完全追加されます！",
    "No Desktop Shortcut on Windows 11?": "デスクトップにアプリが表示されませんか？",
    "Windows Chrome installs PWAs quietly. If missing on desktop: open chrome://apps in Chrome, right-click 'Melkban' -> 'Create shortcut' -> check 'Desktop'. Or simply search for the app name in your Windows Start Menu.": "Chromeは自動処理を行います。見つからない場合は chrome://apps を開き、ショートカットを作成をチェックしてください。",
    "Got it": "終了する",
    "Install Instantly": "アプリの即時インストール"
  },
  ru: {
    "💎 Upgrade to Melkban Gold Agency Panel": "💎 Перейти на Золотую панель агентства Melkban",
    "Go global, access real-time forex indices & utilize unlimited AI engine configurations.": "Выйдите на глобальный рынок. Получите курсы валют и доступ к мощному ИИ без ограничений.",
    "GOLD PREMIUM PERKS": "ЗОЛОТЫЕ ПРЕМИУМ-ПРИВИЛЕГИИ",
    "Live Global Forex Desk": "Актуальные мировые курсы валют",
    "Convert property deeds into Dollar, Euro, Dirham, Afghan Afghani & Turkish Lira instantly.": "Мгновенная конвертация кадастровой стоимости в доллары, евро, дирхамы и афгани.",
    "Unlimited Active Postings": "Безлимитная публикация лотов",
    "Bypass the 2-listing limitation completely. Host an endless catalog of premium cadastral items.": "Снимите ограничение на два лота. Выставляйте сколько угодно элитных объектов недвижимости.",
    "4-Engine AI Consultation Suite": "4 профильных движка ИИ-помощника",
    "Unlock expert investment ROIs, materials checkups, and area statistical breakdowns.": "Прогноз доходности CAGR за 5 лет, энергоэффективность и детальный ИИ-анализ местности.",
    "Gold Verified Trusted Badge": "Золотой знак «Проверенного Брокера»",
    "Instill supreme buyer trust. Get labeled as a verified municipal broker with golden checkmarks.": "Заслужите безграничное доверие покупателей благодаря верифицированной метке.",
    "Advanced Export Options": "Продвинутый экспорт в PDF и Excel",
    "Compile valuation portfolios into presentable client documents with customizable contact grids.": "Экспортируйте выписки и кадастровый анализ в презентабельные файлы за один клик.",
    "ACTIVATION DETAILS": "ДАННЫЕ ОБ ОПЛАТЕ И СЧЕТУ",
    "✉️ Broker Account Email:": "✉️ Рабочий электронный адрес аккаунта:",
    "💳 Select Secure Checkout Method:": "💳 Выберите безопасный способ оплаты:",
    "Debit Card": "Банковская карта (Система Шетаб)",
    "Tether USDT": "Криптовалюта (Tether USDT)",
    "Gold Base Subscription:": "Базовая цена золотой подписки:",
    "🎁 Global Site Discount:": "🎁 Общая скидка от платформы:",
    "Your Promo Code Discount:": "Скидка по вашему коду:",
    "Net Payable Total:": "Итого к оплате к зачислению:",
    "🎫 Special Promo Code:": "🎫 Специальный промокод:",
    "Verify": "Проверить",
    "💳 Destination Admin Bank Card Number:": "💳 16-значная карта администратора назначения:",
    "✓ Transfer subscription fee to the admin card above and input your sender card info below.": "✓ Переведите указанную плату и запишите параметры транзакции ниже.",
    "👤 Your 16-Digit Sender Card Number:": "👤 Номер вашей платежной карты (16 цифр):",
    "👤 Cardholder Name:": "👤 Имя держателя карты:",
    "📸 Upload Transfer Document (Receipt/Slip Photo):": "📸 Загрузите квитанцию или скриншот платежа:",
    "Document attached successfully": "Документ об оплате успешно принят",
    "Click to select or drag & drop slip file": "Нажмите, чтобы загрузить, или перетащите файл",
    "(Allowed types: JPG, PNG, PDF)": "(Разрешенные типы: JPG, PNG, PDF)",
    "USDT address (TRC-20):": "Адрес USDT кошелька компании (TRC-20):",
    "✓ Deposit USDT inside the cadastral vault and trigger approval ledger.": "✓ После подтверждения платежа запустите золотую верификацию внизу.",
    "💡 Cadastral cloud profiles are compiled in local sandbox caching and dynamic system memory, instantly upgrading server responses across and updating layouts.": "💡 Облачная система мгновенно идентифицирует авторизацию и активирует ваш Gold статус.",
    "Cancel": "Отменить изменения",
    "Submit & Launch Gold Pro Class": "Запустить «Золотой» премиум-аккаунт",
    "Verifying & Committing Golden Ledger...": "Идет сопоставление данных и запись в реестр...",
    "🎉 Congratulations! Ariana Gold Subscription Activated!": "🎉 Поздравляем! Ваша золотая подписка успешно активна!",
    "Your real estate agency account is now in Gold premium status. Live world exchange rates, specialized AI engines, and limitless listings are fully unlocked.": "Вам открыт полный доступ к золотым опциям, форекс конвертеру и ИИ-аналитике.",
    "Active Member Profile:": "Зарегистрированный логин профиля:",
    "Access Level:": "Текущий категорийный статус:",
    "GOLD CADASTRAL PRO": "Официальный представитель PRO (GOLD)",
    "Expires at:": "Срок юридической лицензии:",
    "Excellent, Start Using Gold Features": "Отлично, начать работу",
    "🛡️ Continuous blockchain encryption & municipal standard validation is guaranteed.": "🛡️ Любая транзакция защищена интеллектуальным блокчейном.",
    "Install App": "Установить приложение",
    "Install Our App": "Установить на домашний экран",
    "Install Ariana Rahnuma Premium App": "Скачать официальное PWA приложение",
    "Install our fast web-app shortcut registry. Gain instant, non-browser entry to cadastral maps and AI assistants with a dedicated application icon on your homescreen.": "Установите облегченное приложение на рабочий экран, чтобы открывать карты без входа в браузер.",
    "Google Sandbox Frame Active": "Защищенная среда Google Sandbox активна",
    "Direct PWA installation handles are disabled inside nested sandboxed frames due to Chrome security policies inside iframe. Press the golden button below to launch an independent browser context, open in a new tab, and install instantly.": "Установка заблокирована из-за мер безопасности контейнера. Нажмите на золотую клавишу, чтобы открыть в отдельном окне и установить.",
    "Launch Standalone & Install Easily": "Запустить в независимом окне и установить",
    "Open this page in Safari browser, then tap the 'Share' tool at the bottom.": "Нажмите кнопку «Поделиться» (иконка со стрелочкой) внизу браузера Safari.",
    "Scroll down the list and select the 'Add to Home Screen' action.": "В выпадающем меню выберите пункт «На экран Домой» (Add to Home Screen).",
    "Click 'Add' on the upper corner of your screen to conclude setting the shortcut.": "Нажмите на кнопку «Добавить» в правом верхнем углу для создания иконки.",
    "Click our green 'Install' header button, or expand the browser menu button (⋮).": "Нажмите верхнюю зеленую кнопку «Установить» либо откройте свойства браузера (⋮).",
    "Locate and toggle the 'Install app' or 'Add to Home screen' trigger.": "Выберите строчку «Установить приложение» или «Добавить на домашний экран».",
    "Confirm the prompt. The operating system will complete setup as a standalone tool!": "Подтвердите запрос. Приложение будет зафиксировано на экран мобильного устройства!",
    "No Desktop Shortcut on Windows 11?": "Иконка пропала на рабочем столе Windows 11?",
    "Windows Chrome installs PWAs quietly. If missing on desktop: open chrome://apps in Chrome, right-click 'Melkban' -> 'Create shortcut' -> check 'Desktop'. Or simply search for the app name in your Windows Start Menu.": "Перейдите на страницу chrome://apps в Chrome и настройте автоматическое создание значка.",
    "Got it": "Понятно, закрыть",
    "Install Instantly": "Быстрая установка"
  },
  uz: {
    "💎 Upgrade to Melkban Gold Agency Panel": "💎 Melkban oltin brokerlik hisobiga o'tish",
    "Go global, access real-time forex indices & utilize unlimited AI engine configurations.": "Global darajaga chiqing. Dunyo valyutalari va sun'iy intellektdan cheksiz foydalaning.",
    "GOLD PREMIUM PERKS": "OLTIN PREMIUM IMTIYOZLARI",
    "Live Global Forex Desk": "Dunyo valyutalari real vaqtda",
    "Convert property deeds into Dollar, Euro, Dirham, Afghan Afghani & Turkish Lira instantly.": "Kadasrt qog'ozlarini sarmoya kurslariga (dollar, evro va boshqalar) onlayn aylantiring.",
    "Unlimited Active Postings": "Cheksiz e'lonlar kiritish",
    "Bypass the 2-listing limitation completely. Host an endless catalog of premium cadastral items.": "Maksimal 2 e'lon cheklovidan butunlay qutuling. Cheksiz e'lon joylang.",
    "4-Engine AI Consultation Suite": "4 ta maxsus sun'iy intellekt hamkori",
    "Unlock expert investment ROIs, materials checkups, and area statistical breakdowns.": "CAGR foyda hisoblagichi, material tahlili va hudud tahlilichisi Gemini interfeysida.",
    "Gold Verified Trusted Badge": "«Ishonchli broker» rasmiy oltin belgisi",
    "Instill supreme buyer trust. Get labeled as a verified municipal broker with golden checkmarks.": "Profil yonida oltin tasdiq belgisi bilan mijozlar ishonchini 140% ga oshiring.",
    "Advanced Export Options": "Hisobotlarni yuklab olish",
    "Compile valuation portfolios into presentable client documents with customizable contact grids.": "Barcha tahliliy ma'lumotlarni bir klikda PDF yoki Excel formatida saqlab oling.",
    "ACTIVATION DETAILS": "TO'LOV VA AKTIVLASHTIRISH TAFSILOTLARI",
    "✉️ Broker Account Email:": "✉️ Brokerlik hisobining elektron manzili:",
    "💳 Select Secure Checkout Method:": "💳 Xavfsiz to'lov uslubini tanlash:",
    "Debit Card": "Bank kartasi (Shetab)",
    "Tether USDT": "Kriptovalyuta (USDT to'lovi)",
    "Gold Base Subscription:": "Boshlang'ich oltin to'lov qiymati:",
    "🎁 Global Site Discount:": "🎁 Saytdagi umumiy aksiya chegirmasi:",
    "Your Promo Code Discount:": "Promokod chegirmasi:",
    "Net Payable Total:": "Yakuniy to'lanadigan summa:",
    "🎫 Special Promo Code:": "🎫 Maxsus promokod (chegirma):",
    "Verify": "Tekshirish",
    "💳 Destination Admin Bank Card Number:": "💳 Qabul qiluvchi boshqaruv kartasi raqami:",
    "✓ Transfer subscription fee to the admin card above and input your sender card info below.": "✓ To'lovni yuqoridagi kartaga o'tkazib, ma'lumotlarni quyida to'ldiring.",
    "👤 Your 16-Digit Sender Card Number:": "👤 Sizning 16-xonali jo'natuvchi karta raqamingiz:",
    "👤 Cardholder Name:": "👤 Karta egasining to'liq ismi:",
    "📸 Upload Transfer Document (Receipt/Slip Photo):": "📸 To'lov hujjat yoki kvitansiya rasmini yuklash:",
    "Document attached successfully": "To'lov cheki muvaffaqiyatli kiritildi",
    "Click to select or drag & drop slip file": "Yuklash uchun bosing yoki faylni bu yerga o'tkazing",
    "(Allowed types: JPG, PNG, PDF)": "(Ruxsat etilgan turlar: JPG, PNG, PDF)",
    "USDT address (TRC-20):": "Tether uzatish manzili (TRC-20):",
    "✓ Deposit USDT inside the cadastral vault and trigger approval ledger.": "✓ USDTni o'tkazib, quyidagi oltin faollashtirish tugmasini bosing.",
    "💡 Cadastral cloud profiles are compiled in local sandbox caching and dynamic system memory, instantly upgrading server responses across and updating layouts.": "💡 Tizim sizning to'lovingizni onlayn tasdiqlab, hisobni oltin statusga o'tkazadi.",
    "Cancel": "Bekor qilish va yopish",
    "Submit & Launch Gold Pro Class": "Ro'yxatdan o'tish va oltin statusni ochish",
    "Verifying & Committing Golden Ledger...": "Ma'lumotlar bazada tekshirilmoqda...",
    "🎉 Congratulations! Ariana Gold Subscription Activated!": "🎉 Tabriklaymiz! Sizning oltin hisobingiz faollashdi!",
    "Your real estate agency account is now in Gold premium status. Live world exchange rates, specialized AI engines, and limitless listings are fully unlocked.": "Hisobingiz muvaffaqiyatli oshirildi. Valyuta konverteri, sun'iy intellekt va cheksiz e'lonlar ochiq.",
    "Active Member Profile:": "Tizimdagi faol foydalanuvchi hisobi:",
    "Access Level:": "Hozirgi a'zolik darajangiz:",
    "GOLD CADASTRAL PRO": "Rasmiy oltin status (GOLD PRO)",
    "Expires at:": "Litsenziya amal qilish muddati:",
    "Excellent, Start Using Gold Features": "Ajoyib, oltin xizmatlardan foydalanish",
    "🛡️ Continuous blockchain encryption & municipal standard validation is guaranteed.": "🛡️ Tranzaksiyalar blokcheyn shifrlash texnologiyasi bilan himoyalangan.",
    "Install App": "Ilovani o'rnatish",
    "Install Our App": "Bosh ekranga ilova joylash",
    "Install Ariana Rahnuma Premium App": "Ariana kadasrt ilovasini o'rnatish",
    "Install our fast web-app shortcut registry. Gain instant, non-browser entry to cadastral maps and AI assistants with a dedicated application icon on your homescreen.": "Tezkor brauzersiz dasturni o'rnating. Uchrashuvlar, xaritalar va sun'iy intellekt kiring.",
    "Google Sandbox Frame Active": "Google Sandbox xavfsiz muhiti faol",
    "Direct PWA installation handles are disabled inside nested sandboxed frames due to Chrome security policies inside iframe. Press the golden button below to launch an independent browser context, open in a new tab, and install instantly.": "Iframe ichida o'rnatish cheklangan. Boshqa mustaqil oynada ochib o'rnatish tugmasini bosing.",
    "Launch Standalone & Install Easily": "Mustaqil oynada ochish va oson o'rnatish",
    "Open this page in Safari browser, then tap the 'Share' tool at the bottom.": "Safarida ushbu sahifani ochib, quyidagi Share tugmasini bosing.",
    "Scroll down the list and select the 'Add to Home Screen' action.": "Ro'yxatdan 'Bosh ekranga qo'shish' (Add to Home Screen) bandini tanlang.",
    "Click 'Add' on the upper corner of your screen to conclude setting the shortcut.": "O'ng burchakdagi 'Qo'shish' (Add) tugmasini bosib yakunlang.",
    "Click our green 'Install' header button, or expand the browser menu button (⋮).": "Tepadagi yashil 'O'rnatish' tugmasini bosing yoki brauzer menyusini (⋮) oching.",
    "Locate and toggle the 'Install app' or 'Add to Home screen' trigger.": "«Ilovani o'rnatish» yoki «Bosh ekranga qo'shish» bandini tanlang.",
    "Confirm the prompt. The operating system will complete setup as a standalone tool!": "So'rovni tasdiqlang. Tizim avtomatik tarzda ilovani smartfoningizga o'rnatadi!",
    "No Desktop Shortcut on Windows 11?": "Ekranda yorliq hosil bo'lmadimi?",
    "Windows Chrome installs PWAs quietly. If missing on desktop: open chrome://apps in Chrome, right-click 'Melkban' -> 'Create shortcut' -> check 'Desktop'. Or simply search for the app name in your Windows Start Menu.": "Chrome ilovani bildirmasdan o'rnatadi. chrome://apps manzilidan yorliq oching.",
    "Got it": "Tushundim, yopish",
    "Install Instantly": "Tezkor yuklash"
  },
  ku: {
    "💎 Upgrade to Melkban Gold Agency Panel": "💎 نوێکردنەوە بۆ پانێڵی بریکارنامەی زێڕینی مەلک‌بان",
    "Go global, access real-time forex indices & utilize unlimited AI engine configurations.": "بچۆ ناو جیهان، بەهای دینار و دۆلار بە زوویی وەربگرە و هۆشیاری بێسنوور بەکاربهێنە.",
    "GOLD PREMIUM PERKS": "تایبەتمەندیا فەرمی زێڕین",
    "Live Global Forex Desk": "مەتبەخی ته‌سعیری زووی جیهانی",
    "Convert property deeds into Dollar, Euro, Dirham, Afghan Afghani & Turkish Lira instantly.": "گۆڕینی فەرمی تێچووی زەوی و باڵەخانە بۆ دۆلار، یۆرۆ، دینار، درهەم و لیرە.",
    "Unlimited Active Postings": "ناوونووس کردنی بێسنووری خانووبەرە",
    "Bypass the 2-listing limitation completely. Host an endless catalog of premium cadastral items.": "لابردنی فەرمی سنووری ۲ بڵاوکردنەوە بۆ تۆمار کردنی بێ سنوور.",
    "4-Engine AI Consultation Suite": "۴ مۆدێلی تایبەتی هۆشی دەستکرد بۆ ڕێنمایی",
    "Unlock expert investment ROIs, materials checkups, and area statistical breakdowns.": "پێشبینی ڕێژەی قازانج، جۆری کەرەستە و شیکردنەوەی خێرا بە هۆشی کۆنراد Gemini.",
    "Gold Verified Trusted Badge": "نیشانەی فەرمی «بریکاری باوەڕپێکراو»",
    "Instill supreme buyer trust. Get labeled as a verified municipal broker with golden checkmarks.": "بینینی نیشانەی فەرمی زێڕین لە پڕۆفایلی خۆتدا بۆ بەدەستهێنانی متمانەی کڕیار بە ڕێژەی ۱۴۰٪.",
    "Advanced Export Options": "خستنەدەر بە PDF و Excel",
    "Compile valuation portfolios into presentable client documents with customizable contact grids.": "دروست کردنی ڕاپۆرتی بێسنوور بۆ کلاینت بە یەک کلیک بە شێوازی PDF و Excel.",
    "ACTIVATION DETAILS": "زانیاری فاکتۆر و چالاککردن",
    "✉️ Broker Account Email:": "✉️ ئیمەیڵی فەرمی بریکارنامە:",
    "💳 Select Secure Checkout Method:": "💳 شیوازی پارەدانی بێ ترس هەڵبژێرە:",
    "Debit Card": "کارت شێتابی بانکی",
    "Tether USDT": "دراوی دەستکرد (USDT)",
    "Gold Base Subscription:": "نرخی بنەڕەتی متمانەی زێڕین:",
    "🎁 Global Site Discount:": "🎁 داشکاندنی گشتی لە سەرانسەری ماڵپەڕدا:",
    "Your Promo Code Discount:": "داشکاندنی کۆدی پرۆمۆ:",
    "Net Payable Total:": "کۆی تێچووی کۆتایی:",
    "🎫 Special Promo Code:": "🎫 کۆدی داشکاندنی تایبەت (پرۆمۆ):",
    "Verify": "پشکنین",
    "💳 Destination Admin Bank Card Number:": "💳 ژمارەی کارتی ۱۶ ژمارەیی سەرپەرشتیار:",
    "✓ Transfer subscription fee to the admin card above and input your sender card info below.": "✓ پارەکە بۆ کارتی سەرەوە بنێرە و پاشان زانیاری کارتەکەت لێرە بنووسە.",
    "👤 Your 16-Digit Sender Card Number:": "👤 ژمارەی کارتی ۱۶ ژمارەیی تۆ:",
    "👤 Cardholder Name:": "👤 ناوی خاوەن کارتی بانکی:",
    "📸 Upload Transfer Document (Receipt/Slip Photo):": "📸 بارکردنی وێنەی فیش/پسوولەی پارەدان:",
    "Document attached successfully": "پسوولەی پارەدان بە فەرمی بەسترا",
    "Click to select or drag & drop slip file": "بۆ بارکردنی پسوولە لێرە کلیک بکە یان ڕایبکێشە",
    "(Allowed types: JPG, PNG, PDF)": "(فۆرماتە ڕێگەپێدراوەکان: JPG, PNG, PDF)",
    "USDT address (TRC-20):": "ناونیشانی جزدانی تەتەر (TRC-20):",
    "✓ Deposit USDT inside the cadastral vault and trigger approval ledger.": "✓ کاتێک دڵنیابوویتەوە لە ناردنی تێتەر، کلیلی چالاک دابگرە.",
    "💡 Cadastral cloud profiles are compiled in local sandbox caching and dynamic system memory, instantly upgrading server responses across and updating layouts.": "💡 پرۆفایلی نوێی زێڕینی تۆ ڕاستەوخۆ چالاک دەبێت له ڕێگای سیستەمی کۆمپیوتەری هەور.",
    "Cancel": "پاشگەزبوونەوە / داخستن",
    "Submit & Launch Gold Pro Class": "خەزن کردن و دەستپێکردنی زێڕین فەرمی",
    "Verifying & Committing Golden Ledger...": "پشکنینی کۆتایی فاکتۆر...",
    "🎉 Congratulations! Ariana Gold Subscription Activated!": "🎉 پیرۆزە! بەشی زێڕینی ئاریانا بە سەرکەوتوویی بۆتۆ چالاک کرا!",
    "Your real estate agency account is now in Gold premium status. Live world exchange rates, specialized AI engines, and limitless listings are fully unlocked.": "ئەکاونتی تۆ بوو بە زێڕین. گۆڕینەوەی جیهانی زاراوە و هۆشی دەستکرد کرانەوە.",
    "Active Member Profile:": "ئیمەیڵی فەرمی بریکار:",
    "Access Level:": "جۆری ئەندامێتی ئێستا:",
    "GOLD CADASTRAL PRO": "بریکاری زێڕینی فەرمی (GOLD PRO)",
    "Expires at:": "ماوەی بەسەرچوونی لایسنس:",
    "Excellent, Start Using Gold Features": "زۆرباشە، دەستپێکردن بە بەکارهێنان",
    "🛡️ Continuous blockchain encryption & municipal standard validation is guaranteed.": "🛡️ ناردنی پارە بە فەرمی ته‌شفیر کراوە بە بلاکچەین.",
    "Install App": "داگرتنی ئاپڵیکەیشن",
    "Install Our App": "دامەزراندنی کورتەکراوەی هۆم",
    "Install Ariana Rahnuma Premium App": "دامەزراندنی بەرنامەی فەرمی ئاریانا ڕێنوێن",
    "Install our fast web-app shortcut registry. Gain instant, non-browser entry to cadastral maps and AI assistants with a dedicated application icon on your homescreen.": "ڕێگای خێرای کاداستر دابگرە بۆ ئەوەی پێویستت بە کردنەوەی بەردەوامی وێبگەڕ نەبێت.",
    "Google Sandbox Frame Active": "سندوقی پاراستنی تایبەتی گۆگڵ کاردەکات",
    "Direct PWA installation handles are disabled inside nested sandboxed frames due to Chrome security policies inside iframe. Press the golden button below to launch an independent browser context, open in a new tab, and install instantly.": "بەهۆی ڕێکارە نوێیەکانی گوگل ڕاستەوخۆ دانامەزرێت. کلیلی زێڕینی خوارەوە دابگرە بۆ نوێ.",
    "Launch Standalone & Install Easily": "کردنەوە لە پەڕەی جیاواز و دامەزراندنی خۆڕایی",
    "Open this page in Safari browser, then tap the 'Share' tool at the bottom.": "لاپەڕەکە له Safari بکەرەوە و دوگمەی لای خوارەوەی هاوبەش کردن (Share) دابگرە.",
    "Scroll down the list and select the 'Add to Home Screen' action.": "لە نێو لیستەکەدا بژاردەی 'Add to Home Screen' هەڵبژێرە.",
    "Click 'Add' on the upper corner of your screen to conclude setting the shortcut.": "دوگمەی (Add) لە لای ڕاست دابگرە بۆ دروستکردنی وێنۆچکە.",
    "Click our green 'Install' header button, or expand the browser menu button (⋮).": "سەوزی سەرەوە دابگرە یان مینیۆی سێ خاڵی وێبگەڕەکەت (⋮) بکەرەوە.",
    "Locate and toggle the 'Install app' or 'Add to Home screen' trigger.": "بژاردەی دامەزراندنی بەرنامە (Install app) هەڵبژێرە.",
    "Confirm the prompt. The operating system will complete setup as a standalone tool!": "پشتڕاستکردنەوە دابگرە، سیستەمەکە کورتەکراوە فەرمییەکە بۆ مۆبایلەکەت زەخت دەکات!",
    "No Desktop Shortcut on Windows 11?": "وێنۆچکەکە دروست نەبوو لە سەر شاشەی کۆمپیوتەر؟",
    "Windows Chrome installs PWAs quietly. If missing on desktop: open chrome://apps in Chrome, right-click 'Melkban' -> 'Create shortcut' -> check 'Desktop'. Or simply search for the app name in your Windows Start Menu.": "کرۆم هێمن دادەمەزرێنێت. بڕۆ بۆ chrome://apps بۆ سازدانی کورتەکراوە لە دێسکتۆپ.",
    "Got it": "باشە، داخستن",
    "Install Instantly": "دامەزراندنی توندوتۆڵ"
  },
  de: {
    "💎 Upgrade to Melkban Gold Agency Panel": "💎 Upgrade zum Melkban Gold-Vermittler-Panel",
    "Go global, access real-time forex indices & utilize unlimited AI engine configurations.": "Gehen Sie global, greifen Sie auf Devisenkurse in Echtzeit zu & nutzen Sie unbegrenzte KI-Module.",
    "GOLD PREMIUM PERKS": "GOLD PREMIUM PRIVILEGIEN",
    "Live Global Forex Desk": "Live-Devisenplattform",
    "Convert property deeds into Dollar, Euro, Dirham, Afghan Afghani & Turkish Lira instantly.": "Konvertieren Sie Eigentumsurkunden sofort in Dollar, Euro, Dirham oder Afgani.",
    "Unlimited Active Postings": "Unbegrenzte aktive Immobilienanzeigen",
    "Bypass the 2-listing limitation completely. Host an endless catalog of premium cadastral items.": "Legen Sie das 2er-Inseratslimit vollständig ab. Hosten Sie unbegrenzt cadastrale Urkunden.",
    "4-Engine AI Consultation Suite": "4 KI-Assistenten-Systeme",
    "Unlock expert investment ROIs, materials checkups, and area statistical breakdowns.": "CAGR-Rendite-Ermittlung über 5 Jahre, Energiequalität und KI-Umfeld-Diagnosen.",
    "Gold Verified Trusted Badge": "Goldenes Zertifikat „Verifizierter Makler“",
    "Instill supreme buyer trust. Get labeled as a verified municipal broker with golden checkmarks.": "Erzeugen Sie maximales Käufervertrauen durch goldene Kennzeichnung.",
    "Advanced Export Options": "Erweiterter Export in PDF und Excel",
    "Compile valuation portfolios into presentable client documents with customizable contact grids.": "Drucken Sie Standort-Analysen und Immobiliendaten mit einem Klick in PDF oder Excel aus.",
    "ACTIVATION DETAILS": "AKTIVIERUNGSDETAILS UND RECHNUNG",
    "✉️ Broker Account Email:": "✉️ E-Mail-Adresse des Maklerkontos:",
    "💳 Select Secure Checkout Method:": "💳 Wählen Sie Ihre sichere Zahlungsmethode:",
    "Debit Card": "Debitkarte (Schtab-Netzwerk)",
    "Tether USDT": "Kryptowährung (USDT)",
    "Gold Base Subscription:": "Grundpreis des Gold-Abonnements:",
    "🎁 Global Site Discount:": "🎁 Allgemeiner Rabatt der Plattform:",
    "Your Promo Code Discount:": "Rabatt durch Promo-Code:",
    "Net Payable Total:": "Endgültiger Zahlungsbetrag:",
    "🎫 Special Promo Code:": "🎫 Spezieller Werbecode (Promo):",
    "Verify": "Prüfen",
    "💳 Destination Admin Bank Card Number:": "💳 16-stellige Empfängerkarte des Administrators:",
    "✓ Transfer subscription fee to the admin card above and input your sender card info below.": "✓ Senden Sie die Aktivierungsgebühr an die Karte oben und tragen Sie Ihre Daten unten ein.",
    "👤 Your 16-Digit Sender Card Number:": "👤 Ihre 16-stellige Absenderkartennummer:",
    "👤 Cardholder Name:": "👤 Name des Karteninhabers:",
    "📸 Upload Transfer Document (Receipt/Slip Photo):": "📸 Zahlungsnachweis oder Screenshot hochladen:",
    "Document attached successfully": "Überweisungsbeleg erfolgreich angehängt",
    "Click to select or drag & drop slip file": "Klicken zum Hochladen oder Datei hierher ziehen",
    "(Allowed types: JPG, PNG, PDF)": "(Erlaubte Dateitypen: JPG, PNG, PDF)",
    "USDT address (TRC-20):": "Tether(USDT)-Empfangsadresse (TRC-20):",
    "✓ Deposit USDT inside the cadastral vault and trigger approval ledger.": "✓ Drücken Sie nach erfolgreicher Überweisung die Bestätigungstaste unten.",
    "💡 Cadastral cloud profiles are compiled in local sandbox caching and dynamic system memory, instantly upgrading server responses across and updating layouts.": "💡 Die Cloud-Prüfung validiert Ihre Zahlung zeitnah und setzt Sie auf Status Gold.",
    "Cancel": "Abbrechen und Zurück",
    "Submit & Launch Gold Pro Class": "Absenden & Gold Pro Member starten",
    "Verifying & Committing Golden Ledger...": "Zahlung wird abgeglichen & im Journal erfasst...",
    "🎉 Congratulations! Ariana Gold Subscription Activated!": "🎉 Gratulation! Ariana Gold ist nun aktiviert!",
    "Your real estate agency account is now in Gold premium status. Live world exchange rates, specialized AI engines, and limitless listings are fully unlocked.": "Ihr Account befindet sich jetzt auf dem Niveau Gold. Globale Devisen und KI-Module sind freigeschaltet.",
    "Active Member Profile:": "Aktiver Mitgliedskonto-Login:",
    "Access Level:": "Aktueller Account-Rang:",
    "GOLD CADASTRAL PRO": "GOLD-ZERTIFIZIERTES PRO-MITGLIED (GOLD PRO)",
    "Expires at:": "Gesetzliche Lizenzgültigkeit:",
    "Excellent, Start Using Gold Features": "Hervorragend, Gold-Funktionen starten",
    "🛡️ Continuous blockchain encryption & municipal standard validation is guaranteed.": "🛡️ Alle Übertragungen sind durch Blockchain-Kryptografie vollständig gesichert.",
    "Install App": "App installieren",
    "Install Our App": "Zum Startbildschirm hinzufügen",
    "Install Ariana Rahnuma Premium App": "Offizielle Ariana App installieren",
    "Install our fast web-app shortcut registry. Gain instant, non-browser entry to cadastral maps and AI assistants with a dedicated application icon on your homescreen.": "Installieren Sie das Web-App-Symbol auf Ihrem Desktop, um ohne Browser direkt auf Karten zuzugreifen.",
    "Google Sandbox Frame Active": "Google Sandbox Sicherheitsschutz aktiv",
    "Direct PWA installation handles are disabled inside nested sandboxed frames due to Chrome security policies inside iframe. Press the golden button below to launch an independent browser context, open in a new tab, and install instantly.": "Direkte PWA-Installation ist im Iframe-Modus blockiert. Nutzen Sie den goldenen Knopf, um in neuem Fenster direkt zu installieren.",
    "Launch Standalone & Install Easily": "Im separaten Fenster starten & bequem installieren",
    "Open this page in Safari browser, then tap the 'Share' tool at the bottom.": "Öffnen Sie die App in Safari und drücken Sie die Share-Schaltfläche unten.",
    "Scroll down the list and select the 'Add to Home Screen' action.": "Wählen Sie im Popup-Menü „Zum Home-Bildschirm“ (Add to Home Screen).",
    "Click 'Add' on the upper corner of your screen to conclude setting the shortcut.": "Drücken Sie oben rechts auf „Hinzufügen“ (Add) zur Einrichtung.",
    "Click our green 'Install' header button, or expand the browser menu button (⋮).": "Klicken Sie auf den grünen Installationsknopf oben oder das Menü (⋮).",
    "Locate and toggle the 'Install app' or 'Add to Home screen' trigger.": "Wählen Sie „App installieren“ oder „Zum Startbildschirm hinzufügen“.",
    "Confirm the prompt. The operating system will complete setup as a standalone tool!": "Bestätigen Sie; das Betriebssystem legt die Verknüpfung direkt an!",
    "No Desktop Shortcut on Windows 11?": "Kein Icon auf dem Windows 11 Desktop?",
    "Windows Chrome installs PWAs quietly. If missing on desktop: open chrome://apps in Chrome, right-click 'Melkban' -> 'Create shortcut' -> check 'Desktop'. Or simply search for the app name in your Windows Start Menu.": "Chrome speichert oft im Hintergrund. Öffnen Sie chrome://apps zur manuellen Anlage.",
    "Got it": "Verstanden, Schließen",
    "Install Instantly": "Direkte Installation"
  },
  fr: {
    "💎 Upgrade to Melkban Gold Agency Panel": "💎 Passer au panneau d'agence Melkban Gold",
    "Go global, access real-time forex indices & utilize unlimited AI engine configurations.": "Devenez mondial, accédez aux taux de change en temps réel et profitez d'analyses IA illimitées.",
    "GOLD PREMIUM PERKS": "PRIVILÈGES EXCLUSIFS DE L'ABONNEMENT GOLD",
    "Live Global Forex Desk": "Convertisseur de devises mondial en direct",
    "Convert property deeds into Dollar, Euro, Dirham, Afghan Afghani & Turkish Lira instantly.": "Convertissez instantanément les valeurs cadastrales en dollars, euros, dirhams et autres devises.",
    "Cancel": "Annuler",
    "Got it": "Compris",
    "Install Our App": "Installer l'application",
    "Install Ariana Rahnuma Premium App": "Installer l'application Ariana Rahnuma",
    "Install Instantly": "Installer instantanément"
  },
  es: {
    "💎 Upgrade to Melkban Gold Agency Panel": "💎 Actualizar al panel de agencia Melkban Gold",
    "Go global, access real-time forex indices & utilize unlimited AI engine configurations.": "Sea global, acceda a tasas de cambio en tiempo real y disfrute de un motor IA ilimitado.",
    "GOLD PREMIUM PERKS": "BENEFICIOS EXCLUSIVOS DE LA MEMBRESÍA GOLD",
    "Live Global Forex Desk": "Mesa de divisas global en directo",
    "Convert property deeds into Dollar, Euro, Dirham, Afghan Afghani & Turkish Lira instantly.": "Convierta valores de propiedades a dólares, euros, dírhams y más al instante.",
    "Cancel": "Cancelar",
    "Got it": "Entendido",
    "Install Our App": "Instalar aplicación",
    "Install Ariana Rahnuma Premium App": "Instalar aplicación Ariana Rahnuma",
    "Install Instantly": "Instalar al instante"
  }
};


// Load cache from sessionStorage for cross-page persistence
try {
  const saved = sessionStorage.getItem("ariana_translation_cache");
  if (saved) {
    Object.assign(translationCache, JSON.parse(saved));
  }
} catch (e) {
  console.warn("Storage access not available:", e);
}

function saveCache() {
  try {
    sessionStorage.setItem("ariana_translation_cache", JSON.stringify(translationCache));
  } catch (e) {
    // ignore
  }
}

/**
 * Returns a translation for a given text into the target language.
 * Checks in-memory cache first, then calls the AI translation server.
 */
export async function translateText(text: string, targetLang: Language): Promise<string> {
  const trimmed = text.trim();
  if (!trimmed) return "";
  
  // Instant high-fidelity lookup resolution
  if (
    OFFLINE_TEXT_DICTIONARY[targetLang] &&
    OFFLINE_TEXT_DICTIONARY[targetLang][trimmed] !== undefined
  ) {
    return OFFLINE_TEXT_DICTIONARY[targetLang][trimmed];
  }

  // Skip translation if language is Farsi/Arabic and text already has Persian letters
  if (targetLang === "fa" && /[\u0600-\u06FF]/.test(trimmed)) {
    return trimmed;
  }

  // If target is English or Persian and the source text already seems to be in it, or is very short,
  // we first check cache.
  const cacheKey = `${targetLang}:${trimmed}`;
  if (translationCache[cacheKey]) {
    return translationCache[cacheKey];
  }

  // Skip translation if language is EN / FA and text is already similar, but better is to let Gemini do it
  if (targetLang === "en" && /^[a-zA-Z0-9\s.,!?-]+$/.test(trimmed)) {
    return trimmed;
  }

  try {
    const res = await fetch("/api/translate", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ text: trimmed, targetLang }),
    });

    if (res.ok) {
      const data = await res.json();
      if (data.result && typeof data.result === "string") {
        translationCache[cacheKey] = data.result;
        saveCache();
        return data.result;
      }
    }
  } catch (err) {
    console.error("Failed to fetch translation for:", trimmed, err);
  }

  return trimmed; // Safely fall back to the original text
}

/**
 * Batch translation of multiple strings to optimize API calls
 */
export async function translateBatch(texts: string[], targetLang: Language): Promise<string[]> {
  const results: string[] = [];
  const indexesToTranslate: number[] = [];
  const textsToTranslate: string[] = [];

  texts.forEach((text, idx) => {
    const t = text.trim();
    const cacheKey = `${targetLang}:${t}`;
    
    if (OFFLINE_TEXT_DICTIONARY[targetLang] && OFFLINE_TEXT_DICTIONARY[targetLang][t] !== undefined) {
      results[idx] = OFFLINE_TEXT_DICTIONARY[targetLang][t];
    } else if (translationCache[cacheKey]) {
      results[idx] = translationCache[cacheKey];
    } else if (targetLang === "fa" && /[\u0600-\u06FF]/.test(t)) {
      results[idx] = t;
    } else {
      indexesToTranslate.push(idx);
      textsToTranslate.push(t);
    }
  });

  if (textsToTranslate.length === 0) {
    return results;
  }

  try {
    const res = await fetch("/api/translate", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ text: textsToTranslate, targetLang }),
    });

    if (res.ok) {
      const data = await res.json();
      if (data.result && Array.isArray(data.result)) {
        data.result.forEach((val: string, idx: number) => {
          const originalIdx = indexesToTranslate[idx];
          const cacheKey = `${targetLang}:${textsToTranslate[idx]}`;
          translationCache[cacheKey] = val;
          results[originalIdx] = val;
        });
        saveCache();
        return results;
      }
    }
  } catch (err) {
    console.error("Dynamic batch translation failed:", err);
  }

  // Fallback to individual fallback or original
  indexesToTranslate.forEach((originalIdx, idx) => {
    results[originalIdx] = textsToTranslate[idx];
  });
  return results;
}
