import { CountryConfig, Property } from "./types";

export const COUNTRIES: CountryConfig[] = [
  {
    code: "AE",
    nameEn: "United Arab Emirates",
    nameFa: "امارات متحده عربی",
    nameLocal: "الإمارات العربية المتحدة",
    flag: "🇦🇪",
    currency: "AED",
    currencySymbol: "د.إ",
    baseExchangeRate: 15300,
    center: { lat: 25.2048, lng: 55.2708 },
    districts: ["Dubai Marina", "Downtown Dubai", "Palm Jumeirah", "Business Bay", "Jumeirah Beach Residences"]
  },
  {
    code: "SA",
    nameEn: "Saudi Arabia",
    nameFa: "عربستان سعودی",
    nameLocal: "المملكة العربية السعودية",
    flag: "🇸🇦",
    currency: "SAR",
    currencySymbol: "ر.س",
    baseExchangeRate: 15000,
    center: { lat: 24.7136, lng: 46.6753 },
    districts: ["Al-Malqa, Riyadh", "Al-Yasmin, Riyadh", "Al-Shaty, Jeddah", "Al-Hamra, Jeddah", "Olaya, Riyadh"]
  },
  {
    code: "QA",
    nameEn: "Qatar",
    nameFa: "قطر",
    nameLocal: "دولة قطر",
    flag: "🇶🇦",
    currency: "QAR",
    currencySymbol: "ر.ق",
    baseExchangeRate: 15400,
    center: { lat: 25.2854, lng: 51.5310 },
    districts: ["The Pearl-Qatar", "West Bay, Doha", "Lusail City", "Msheireb, Doha", "Al Sadd, Doha"]
  },
  {
    code: "KW",
    nameEn: "Kuwait",
    nameFa: "کویت",
    nameLocal: "دولة الكويت",
    flag: "🇰🇼",
    currency: "KWD",
    currencySymbol: "د.ك",
    baseExchangeRate: 185000,
    center: { lat: 29.3759, lng: 47.9774 },
    districts: ["Salmiya", "Sharq, Kuwait City", "Hawally", "Jabriya", "Bneid Al-Gar"]
  },
  {
    code: "BH",
    nameEn: "Bahrain",
    nameFa: "بحرین",
    nameLocal: "مملكة البحرين",
    flag: "🇧🇭",
    currency: "BHD",
    currencySymbol: "د.ب",
    baseExchangeRate: 150005,
    center: { lat: 26.2285, lng: 50.5860 },
    districts: ["Amwaj Islands", "Juffair, Manama", "Seef, Manama", "Riffa", "Adliya, Manama"]
  },
  {
    code: "OM",
    nameEn: "Oman",
    nameFa: "عمان",
    nameLocal: "سلطنة عمان",
    flag: "🇴🇲",
    currency: "OMR",
    currencySymbol: "ر.ع.",
    baseExchangeRate: 148000,
    center: { lat: 23.5859, lng: 58.4059 },
    districts: ["Al Mouj, Muscat", "Qurum, Muscat", "Azaiba, Muscat", "Madinat Al Ilam", "Shatti Al Qurum"]
  },
  {
    code: "IQ",
    nameEn: "Iraq",
    nameFa: "عراق",
    nameLocal: "جمهورية العراق",
    flag: "🇮🇶",
    currency: "IQD",
    currencySymbol: "د.ع",
    baseExchangeRate: 45,
    center: { lat: 33.3152, lng: 44.3661 },
    districts: ["Al-Mansour, Baghdad", "Karrada, Baghdad", "Erbil Royal City", "Dream City, Erbil", "Basra Gate"]
  },
  {
    code: "EG",
    nameEn: "Egypt",
    nameFa: "مصر",
    nameLocal: "جمهورية مصر العربية",
    flag: "🇪🇬",
    currency: "EGP",
    currencySymbol: "ج.م",
    baseExchangeRate: 1200,
    center: { lat: 30.0444, lng: 31.2357 },
    districts: ["New Cairo", "Zamalek, Cairo", "Sheikh Zayed City", "Maadi, Cairo", "Heliopolis"]
  },
  {
    code: "SY",
    nameEn: "Syria",
    nameFa: "سوریه",
    nameLocal: "الجمهورية العربية السورية",
    flag: "🇸🇾",
    currency: "SYP",
    currencySymbol: "ل.س",
    baseExchangeRate: 5,
    center: { lat: 33.5138, lng: 36.2765 },
    districts: ["Al-Mazza, Damascus", "Abu Rummaneh, Damascus", "Malki, Damascus", "Shahba, Aleppo", "Lattakia Center"]
  },
  {
    code: "LB",
    nameEn: "Lebanon",
    nameFa: "لبنان",
    nameLocal: "الجمهورية اللبنانية",
    flag: "🇱🇧",
    currency: "LBP",
    currencySymbol: "ل.ل",
    baseExchangeRate: 0.7,
    center: { lat: 33.8938, lng: 35.5018 },
    districts: ["Achrafieh, Beirut", "Verdun, Beirut", "Downtown Beirut", "Hamra, Beirut", "Jounieh"]
  },
  {
    code: "JO",
    nameEn: "Jordan",
    nameFa: "اردن",
    nameLocal: "المملكة الأردنية الهاشمية",
    flag: "🇯🇴",
    currency: "JOD",
    currencySymbol: "د.ا",
    baseExchangeRate: 80000,
    center: { lat: 31.9522, lng: 35.9106 },
    districts: ["Abdoun, Amman", "Dabouq, Amman", "Al-Rabiah, Amman", "Sweifieh, Amman", "Khalda"]
  },
  {
    code: "MA",
    nameEn: "Morocco",
    nameFa: "مراکش",
    nameLocal: "المملكة المغربية",
    flag: "🇲🇦",
    currency: "MAD",
    currencySymbol: "د.م.",
    baseExchangeRate: 5600,
    center: { lat: 34.0208, lng: -6.8301 },
    districts: ["Anfa, Casablanca", "Guéliz, Marrakech", "Riyadh, Rabat", "Hivernage, Marrakech", "Tanger Boulevard"]
  },
  {
    code: "YE",
    nameEn: "Yemen",
    nameFa: "یمن",
    nameLocal: "الجمهورية اليمنية",
    flag: "🇾🇪",
    currency: "YER",
    currencySymbol: "ر.ي",
    baseExchangeRate: 220,
    center: { lat: 15.3694, lng: 44.1910 },
    districts: ["Hadda, Sana'a", "Al-Tawahi, Aden", "Crater, Aden", "Al-Ghaydah", "Taiz City"]
  },
  {
    code: "LY",
    nameEn: "Libya",
    nameFa: "لیبی",
    nameLocal: "دولة ليبيا",
    flag: "🇱🇾",
    currency: "LYD",
    currencySymbol: "د.ل",
    baseExchangeRate: 11500,
    center: { lat: 32.8872, lng: 13.1913 },
    districts: ["Hay Al-Andalus, Tripoli", "Ben Ashour, Tripoli", "Sidi Al-Masri, Tripoli", "Al-Fuwayhat, Benghazi", "Tripoli Center"]
  },
  {
    code: "SD",
    nameEn: "Sudan",
    nameFa: "سودان",
    nameLocal: "جمهورية السودان",
    flag: "🇸🇩",
    currency: "SDG",
    currencySymbol: "ج.س.",
    baseExchangeRate: 100,
    center: { lat: 15.5007, lng: 32.5599 },
    districts: ["Al-Riyadh, Khartoum", "Al-Mansheya, Khartoum", "Amirat, Khartoum", "Khartoum 2", "Omdurman"]
  },
  {
    code: "TN",
    nameEn: "Tunisia",
    nameFa: "تونس",
    nameLocal: "الجمهورية التونسية",
    flag: "🇹🇳",
    currency: "TND",
    currencySymbol: "د.ت",
    baseExchangeRate: 18000,
    center: { lat: 36.8065, lng: 10.1815 },
    districts: ["Les Berges du Lac, Tunis", "La Marsa, Tunis", "Carthage", "Sidi Bou Said", "Hammamet Beach"]
  },
  {
    code: "DZ",
    nameEn: "Algeria",
    nameFa: "الجزایر",
    nameLocal: "الجمهورية الجزائرية الديمقراطية الشعبية",
    flag: "🇩🇿",
    currency: "DZD",
    currencySymbol: "د.ج",
    baseExchangeRate: 420,
    center: { lat: 36.7525, lng: 3.0420 },
    districts: ["Hydra, Algiers", "El Biar, Algiers", "Sidi Yahia, Algiers", "Oran Waterfront", "Constantine"]
  },
  {
    code: "RU",
    nameEn: "Russia",
    nameFa: "روسیه",
    nameLocal: "Россия",
    flag: "🇷🇺",
    currency: "RUB",
    currencySymbol: "₽",
    baseExchangeRate: 630,
    center: { lat: 55.7558, lng: 37.6173 },
    districts: ["Tverskoy, Moscow", "Arbat, Moscow", "Presnensky, Moscow", "Krestovsky Island, St. Petersburg", "Sokolniki"]
  },
  {
    code: "AF",
    nameEn: "Afghanistan",
    nameFa: "افغانستان",
    nameLocal: "افغانستان",
    flag: "🇦🇫",
    currency: "AFN",
    currencySymbol: "؋",
    baseExchangeRate: 810,
    center: { lat: 34.5553, lng: 69.1779 },
    districts: ["Wazir Akbar Khan, Kabul", "Sherpur, Kabul", "Kart-e Sakhi, Kabul", "Herat City Centre", "Mazar-i-Sharif"]
  },
  {
    code: "PK",
    nameEn: "Pakistan",
    nameFa: "پاکستان",
    nameLocal: "پاکستان",
    flag: "🇵🇰",
    currency: "PKR",
    currencySymbol: "₨",
    baseExchangeRate: 210,
    center: { lat: 33.6844, lng: 73.0479 },
    districts: ["DHA Phase 6, Karachi", "F-7, Islamabad", "Gulberg, Lahore", "E-7, Islamabad", "Clifton, Karachi"]
  },
  {
    code: "IN",
    nameEn: "India",
    nameFa: "هند",
    nameLocal: "भारत",
    flag: "🇮🇳",
    currency: "INR",
    currencySymbol: "₹",
    baseExchangeRate: 710,
    center: { lat: 19.0760, lng: 72.8777 },
    districts: ["Malabar Hill, Mumbai", "Jor Bagh, New Delhi", "Koramangala, Bangalore", "Bandra West, Mumbai", "Chanakyapuri, Delhi"]
  },
  {
    code: "TR",
    nameEn: "Turkey",
    nameFa: "ترکیه",
    nameLocal: "Türkiye",
    flag: "🇹🇷",
    currency: "TRY",
    currencySymbol: "₺",
    baseExchangeRate: 1850,
    center: { lat: 41.0082, lng: 28.9784 },
    districts: ["Bebek, Istanbul", "Nisantasi, Istanbul", "Sariyer, Istanbul", "Cankaya, Ankara", "Konak, Izmir"]
  },
  {
    code: "DE",
    nameEn: "Germany",
    nameFa: "آلمان",
    nameLocal: "Deutschland",
    flag: "🇩🇪",
    currency: "EUR",
    currencySymbol: "€",
    baseExchangeRate: 61000,
    center: { lat: 52.5200, lng: 13.4050 },
    districts: ["Mitte, Berlin", "Schwabing, Munich", "Westend, Frankfurt", "Hafencity, Hamburg", "Kreuzberg, Berlin"]
  },
  {
    code: "SG",
    nameEn: "Singapore",
    nameFa: "سنگاپور",
    nameLocal: "Singapore / 新加坡",
    flag: "🇸🇬",
    currency: "SGD",
    currencySymbol: "S$",
    baseExchangeRate: 46200,
    center: { lat: 1.3521, lng: 103.8198 },
    districts: ["Marina Bay", "Orchard Road", "Sentosa Cove", "Bukit Timah", "Tampines"]
  },
  {
    code: "GB",
    nameEn: "United Kingdom",
    nameFa: "بریتانیا",
    nameLocal: "United Kingdom",
    flag: "🇬🇧",
    currency: "GBP",
    currencySymbol: "£",
    baseExchangeRate: 77500,
    center: { lat: 51.5074, lng: -0.1278 },
    districts: ["Mayfair, London", "Kensington, London", "Belgravia, London", "Chelsea, London", "Notting Hill, London"]
  },
  {
    code: "CA",
    nameEn: "Canada",
    nameFa: "کانادا",
    nameLocal: "Canada",
    flag: "🇨🇦",
    currency: "CAD",
    currencySymbol: "C$",
    baseExchangeRate: 45100,
    center: { lat: 43.6532, lng: -79.3832 },
    districts: ["Downtown Vancouver", "Yorkville, Toronto", "Coal Harbour, Vancouver", "Le Plateau, Montreal", "Westmount, Montreal"]
  },
  {
    code: "IR",
    nameEn: "Iran",
    nameFa: "ایران",
    nameLocal: "ایران",
    flag: "🇮🇷",
    currency: "IRR",
    currencySymbol: "ریال",
    baseExchangeRate: 1,
    center: { lat: 35.6892, lng: 51.3890 },
    districts: ["الهیه (Elahiyeh)", "فرشته (Fereshteh)", "نیاوران (Niavaran)", "زعفرانیه (Zaferanieh)", "لواسان (Lavasan)", "کمرانیه (Kamranieh)"]
  }
];

export const INITIAL_PROPERTIES: Property[] = [
  {
    id: "prop-ir-1",
    title: "پنت‌‌هاوس مجلل کلاسیک الهیه - آریانا رهنما (Luxury Penthouse)",
    description: "یک شاهکار معماری لوکس و بی‌نظیر ارائه شده توسط کاداستر الکترونیکی آریانا رهنما. دارای مشاعات تمام هتلینگ، استخر معلق شیشه‌ای، روف گاردن اختصاصی ۳۶۰ درجه با دید ابدی کل پایتخت، متریال تماماً برند وارداتی و سیستم کاملاً هوشمند تپ‌لینک.",
    type: "sale",
    pricePerSqm: 8000,
    totalPrice: 4000000,
    area: 500,
    country: "IR",
    district: "الهیه (Elahiyeh)",
    bedrooms: 4,
    phone: "+982122003300",
    address: "خیابان الهیه، برج باغ مجلل مریم، تهران",
    latitude: 35.7951,
    longitude: 51.4232,
    images: ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600&auto=format&fit=crop&q=80"],
    createdAt: "2026-06-01T12:00:00Z",
    isApproved: true
  },
  {
    id: "prop-ir-2",
    title: "ویلا مدرن استخردار لواسان - خانه لوکس کاداستر آریانا رهنما (Luxury Villa)",
    description: "ویلا مسکونی فوق‌العاده مدرن و لوکس با سند تک‌برگ کاداستر شش‌دانگ آماده انتقال در بهترین نقطه لواسان. خانه لوکس گران‌قیمت کاملاً مجهز با چهار خواب مستر بی نظیر، سالن سینمای خانگی خصوصی، شاه‌نشین سنتی ایرانی و سالن ورزشی مجهز.",
    type: "sale",
    pricePerSqm: 9000,
    totalPrice: 5850000,
    area: 650,
    country: "IR",
    district: "لواسان (Lavasan)",
    bedrooms: 5,
    phone: "+989121112233",
    address: "لواسان بزرگ، محله لاکچری باستی هیلز، پلاک ۱۲",
    latitude: 35.8239,
    longitude: 51.6210,
    images: ["https://images.unsplash.com/photo-1613977257363-707ba9348227?w=600&auto=format&fit=crop&q=80"],
    createdAt: "2026-06-01T15:30:00Z",
    isApproved: true
  },
  {
    id: "prop-ir-3",
    title: "آپارتمان هوشمند برج باغ فرشته - خانه لوکس آریانا رهنما (Smart Apartment)",
    description: "فروش آپارتمان مدرن و لوکس در خیابان فرشته تهران. واحدی ایده‌آل و خانه لوکس کلاسیک با لابی مبله مجلل، نگهبانی ۲۴ ساعته کاداستر آریانا رهنما با بالاترین استانداردهای ایمنی و رفاهی روز دنیا.",
    type: "sale",
    pricePerSqm: 7500,
    totalPrice: 2100000,
    area: 280,
    country: "IR",
    district: "فرشته (Fereshteh)",
    bedrooms: 3,
    phone: "+982122334455",
    address: "خیابان فرشته، خیابان تختی، برج باغ فرشته، تهران",
    latitude: 35.7928,
    longitude: 51.4172,
    images: ["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&auto=format&fit=crop&q=80"],
    createdAt: "2026-06-01T18:00:00Z",
    isApproved: true
  },
  {
    id: "prop-1",
    title: "Luxury Penthouse in Moscow City",
    description: "Elegant modern penthouse inside the Federation Tower with jaw-dropping panoramic views of Moscow. Complete smart-home solutions.",
    type: "sale",
    pricePerSqm: 12000,
    totalPrice: 2400000,
    area: 200,
    country: "RU",
    district: "Presnensky, Moscow",
    bedrooms: 3,
    phone: "+79031204050",
    address: "Presnenskaya Naberezhnaya, 12, Moscow",
    latitude: 55.7485,
    longitude: 37.5376,
    images: ["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&auto=format&fit=crop&q=60"],
    createdAt: "2026-05-20T10:00:00Z",
    isApproved: true
  },
  {
    id: "prop-2",
    title: "Beautiful Villa in Wazir Akbar Khan",
    description: "Highly secure, spacious family diplomatic villa with a beautiful garden, independent office chamber, high boundary walls, and central heating.",
    type: "sale",
    pricePerSqm: 1500,
    totalPrice: 600000,
    area: 400,
    country: "AF",
    district: "Wazir Akbar Khan, Kabul",
    bedrooms: 5,
    phone: "+93799123456",
    address: "Street 15, Wazir Akbar Khan, Kabul",
    latitude: 34.5381,
    longitude: 69.1895,
    images: ["https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=600&auto=format&fit=crop&q=60"],
    createdAt: "2026-05-22T08:30:00Z",
    isApproved: true
  },
  {
    id: "prop-3",
    title: "Modern Executive Apartment in F-7 Islamabad",
    description: "Stylishly furnished premium duplex with stunning Margalla Hills views. Equipped with standard secure access, underground parking, and smart kitchen.",
    type: "rent",
    deposit: 3000,
    rent: 1200,
    area: 160,
    country: "PK",
    district: "F-7, Islamabad",
    bedrooms: 2,
    phone: "+923001234567",
    address: "F-7 Sector Main Boulevard, Islamabad",
    latitude: 33.7225,
    longitude: 73.0560,
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&auto=format&fit=crop&q=60"],
    createdAt: "2026-05-24T12:00:00Z",
    isApproved: true
  },
  {
    id: "prop-4",
    title: "Luxury Sea View Villa at Palm Jumeirah",
    description: "Extraordinary beachfront villa with private pool, direct ocean access, and spectacular views of the Dubai skyline. Hand-crafted marble finishing.",
    type: "sale",
    pricePerSqm: 18000,
    totalPrice: 9000000,
    area: 500,
    country: "AE",
    district: "Palm Jumeirah",
    bedrooms: 4,
    phone: "+971501234567",
    address: "Frond D, Palm Jumeirah, Dubai",
    latitude: 25.1124,
    longitude: 55.1390,
    images: ["https://images.unsplash.com/photo-1613977257363-707ba9348227?w=600&auto=format&fit=crop&q=60"],
    createdAt: "2026-05-25T14:45:00Z",
    isApproved: true
  },
  {
    id: "prop-5",
    title: "High-Rise Sky Mansion in Malabar Hill Mumbai",
    description: "An ultra-premium whole-floor residence facing the Arabian Sea. Private elevator, infinity sky deck, automated climate control, and separate butler room.",
    type: "sale",
    pricePerSqm: 25000,
    totalPrice: 10000000,
    area: 400,
    country: "IN",
    district: "Malabar Hill, Mumbai",
    bedrooms: 4,
    phone: "+919820012345",
    address: "BG Kher Marg, Malabar Hill, Mumbai",
    latitude: 18.9548,
    longitude: 72.7985,
    images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=600&auto=format&fit=crop&q=60"],
    createdAt: "2026-05-26T09:15:00Z",
    isApproved: true
  },
  {
    id: "prop-6",
    title: "Penthouse overlooking Bosphorus Bebek",
    description: "Rare opportunity to lease a breathtaking luxury penthouse with an enormous terrace suspended over the scenic blue Bosphorus straits in Bebek.",
    type: "rent_mortgage",
    deposit: 50000,
    rent: 4000,
    area: 220,
    country: "TR",
    district: "Bebek, Istanbul",
    bedrooms: 3,
    phone: "+905321111111",
    address: "Cevdet Pasa Caddesi, Bebek, Istanbul",
    latitude: 41.0772,
    longitude: 29.0435,
    images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&auto=format&fit=crop&q=60"],
    createdAt: "2026-05-27T11:00:00Z",
    isApproved: true
  },
  {
    id: "prop-7",
    title: "Elegant Duplex Apartment in Berlin Mitte",
    description: "Luxurious industrial-chic design apartment with 6-meter ceiling heights, exposed brick walls, and custom steel frames in the heart of Berlin.",
    type: "sale",
    pricePerSqm: 8500,
    totalPrice: 1020000,
    area: 120,
    country: "DE",
    district: "Mitte, Berlin",
    bedrooms: 2,
    phone: "+493012345678",
    address: "Friedrichstrasse 105, 10117 Berlin",
    latitude: 52.5206,
    longitude: 13.3889,
    images: ["https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&auto=format&fit=crop&q=60"],
    createdAt: "2026-05-27T16:20:00Z",
    isApproved: true
  },
  {
    id: "prop-8",
    title: "Luxury Marina Penthouse, Dubai",
    description: "Breathtaking views of the yacht harbor, customized marble kitchens, private pools, smart home configurations.",
    type: "sale",
    pricePerSqm: 15000,
    totalPrice: 4500000,
    area: 300,
    country: "AE",
    district: "Dubai Marina",
    bedrooms: 4,
    phone: "+971501234567",
    address: "Marina Gate Tower A, Dubai Marina, Dubai",
    latitude: 25.0851,
    longitude: 55.1432,
    images: ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600&auto=format&fit=crop&q=60"],
    createdAt: "2026-05-28T02:10:00Z",
    isApproved: true
  },
  {
    id: "prop-9",
    title: "Chic Canal-Front Residence on Krestovsky Island",
    description: "Exceptional luxury flat situated in the most desirable green secure zone of Saint Petersburg. Private berth, modern gas fireplace, and integrated security guard system.",
    type: "rent",
    deposit: 150000,
    rent: 5200,
    area: 150,
    country: "RU",
    district: "Krestovsky Island, St. Petersburg",
    bedrooms: 2,
    phone: "+79119203040",
    address: "Krestovsky Prospekt, 24, St. Petersburg",
    latitude: 59.9715,
    longitude: 30.2520,
    images: ["https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=600&auto=format&fit=crop&q=60"],
    createdAt: "2026-05-28T04:20:00Z",
    isApproved: true
  },
  {
    id: "prop-10",
    title: "Heritage Mansion & Gardens in Herat Center",
    description: "Stunning classical estate featuring exquisite Traditional Afghan brickwork, central water fountains, private orchards, and fully modern solar system backups.",
    type: "sale",
    pricePerSqm: 800,
    totalPrice: 480000,
    area: 600,
    country: "AF",
    district: "Herat City Centre",
    bedrooms: 6,
    phone: "+93402203040",
    address: "Bagh-e-Dahna Boulevard, Herat",
    latitude: 34.3416,
    longitude: 62.2031,
    images: ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=600&auto=format&fit=crop&q=60"],
    createdAt: "2026-05-28T06:15:00Z",
    isApproved: true
  },
  {
    id: "prop-11",
    title: "Seaside Premium Duplex in Clifton Karachi",
    description: "Breathtaking multi-level ocean-facing residency. Features panoramic shatterproof double-glazed terrace views, imported Italian tile finishings, and standby power generators.",
    type: "sale",
    pricePerSqm: 1800,
    totalPrice: 450000,
    area: 250,
    country: "PK",
    district: "Clifton, Karachi",
    bedrooms: 3,
    phone: "+922134567890",
    address: "Marine Drive Promenade, Block 4, Clifton, Karachi",
    latitude: 24.8138,
    longitude: 67.0336,
    images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=600&auto=format&fit=crop&q=60"],
    createdAt: "2026-05-28T08:45:00Z",
    isApproved: true
  },
  {
    id: "prop-12",
    title: "Diplomatic Enclave Sanctuary in Chanakyapuri",
    description: "Prestigious and secure low-density estate in Delhi's most elite administrative zone. Hand-woven silk wallpapers, private library, manicured British lawns, and filtered air system.",
    type: "rent",
    deposit: 800000,
    rent: 9500,
    area: 380,
    country: "IN",
    district: "Bandra West, Mumbai",
    bedrooms: 4,
    phone: "+911124671122",
    address: "Sardar Patel Marg, Chanakyapuri, New Delhi",
    latitude: 28.5992,
    longitude: 77.1825,
    images: ["https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=600&auto=format&fit=crop&q=60"],
    createdAt: "2026-05-28T09:10:00Z",
    isApproved: true
  },
  {
    id: "prop-13",
    title: "Signature Beachfront Mansion, Jumeirah",
    description: "Exclusive luxury beachfront custom mansion with an infinity pool, private cinema, separate guest wings, and full Dubai skyline access.",
    type: "sale",
    pricePerSqm: 20500,
    totalPrice: 8200000,
    area: 400,
    country: "AE",
    district: "Palm Jumeirah",
    bedrooms: 5,
    phone: "+971509876543",
    address: "Signature Frond P, Palm Jumeirah, Dubai",
    latitude: 25.1124,
    longitude: 55.1390,
    images: ["https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=600&auto=format&fit=crop&q=60"],
    createdAt: "2026-05-28T10:15:00Z",
    isApproved: true
  },
  {
    id: "prop-14",
    title: "Waterfront Glass Penthouse, Doha",
    description: "A spectacular minimal architecture masterpiece with a private suspended glass heated swimming pool, 250 sqm fully equipped terrace garden, and ABB automation system.",
    type: "sale",
    pricePerSqm: 10000,
    totalPrice: 3500000,
    area: 350,
    country: "QA",
    district: "The Pearl-Qatar",
    bedrooms: 3,
    phone: "+97444111222",
    address: "Porto Arabia Promenade Tower 12, Doha",
    latitude: 25.3725,
    longitude: 51.5510,
    images: ["https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=600&auto=format&fit=crop&q=60"],
    createdAt: "2026-05-28T11:45:00Z",
    isApproved: true
  },
  {
    id: "prop-15",
    title: "Bosphorus Dream Mansion in Bebek",
    description: "Exclusive historical waterfront Yalı style mansion. Premium marble interior, direct boat dock access, beautiful landscape architecture with full sea panorama.",
    type: "sale",
    pricePerSqm: 22000,
    totalPrice: 15400000,
    area: 700,
    country: "TR",
    district: "Bebek, Istanbul",
    bedrooms: 6,
    phone: "+905332222222",
    address: "Kebeci Cd. No:8, Bebek, Istanbul",
    latitude: 41.0759,
    longitude: 29.0441,
    images: ["https://images.unsplash.com/photo-1512915922686-57c11dde9b6b?w=600&auto=format&fit=crop&q=60"],
    createdAt: "2026-05-28T14:30:00Z",
    isApproved: true
  },
  {
    id: "prop-16",
    title: "Sophisticated Design Loft in Schwabing",
    description: "Fully modernized luxury penthouse near the Englischer Garten. High-end custom Bulthaup kitchen, oak parquet floors, state of the art wellness sauna.",
    type: "rent",
    deposit: 12000,
    rent: 4500,
    area: 180,
    country: "DE",
    district: "Schwabing, Munich",
    bedrooms: 3,
    phone: "+49891234567",
    address: "Leopoldstraße 78, 80802 München",
    latitude: 48.1611,
    longitude: 11.5856,
    images: ["https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&auto=format&fit=crop&q=60"],
    createdAt: "2026-05-28T16:10:00Z",
    isApproved: true
  },
  {
    id: "prop-17",
    title: "Burj Khalifa Boulevard Ultimate View Apartment",
    description: "Stunning high-floor luxury apartment directly overlooking the Dubai Fountain and Burj Khalifa. Exquisitely furnished by Cavalli, with five-star tower concierge service.",
    type: "sale",
    pricePerSqm: 14000,
    totalPrice: 4200000,
    area: 300,
    country: "AE",
    district: "Downtown Dubai",
    bedrooms: 3,
    phone: "+971509998877",
    address: "Sheikh Mohammed bin Rashid Blvd, Downtown Dubai",
    latitude: 25.1972,
    longitude: 55.2744,
    images: ["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&auto=format&fit=crop&q=60"],
    createdAt: "2026-05-28T18:25:00Z",
    isApproved: true
  },
  {
    id: "prop-18",
    title: "Royal Oasis Estates, Al-Malqa",
    description: "Exquisite modern villa engineered by world-class architects. High double-height ceilings, private botanical courtyard gardens, Olympic-size pool, and professional direct gas fireplaces.",
    type: "sale",
    pricePerSqm: 14000,
    totalPrice: 6860000,
    area: 490,
    country: "SA",
    district: "Al-Malqa, Riyadh",
    bedrooms: 4,
    phone: "+966505060708",
    address: "Al-Malqa Royal Quarter Plot 55, Riyadh",
    latitude: 24.8150,
    longitude: 46.6120,
    images: [
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=600&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=600&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&auto=format&fit=crop&q=80"
    ],
    createdAt: "2026-05-29T10:00:00Z",
    isApproved: true
  },
  {
    id: "prop-19",
    title: "Palatial Golf Course Oasis Villa",
    description: "An extraordinary bespoke villa directly overlooking the lush green fairways in Riyadh. Features a massive double-height grand entrance, custom resort-grade temperature controlled swimming pool, detached VIP office, and a sophisticated internal elevator.",
    type: "sale",
    pricePerSqm: 8500,
    totalPrice: 5100000,
    area: 600,
    country: "SA",
    district: "Al-Malqa, Riyadh",
    bedrooms: 5,
    phone: "+966501234567",
    address: "Al-Malqa Fairways Boulevard, Corner Plot 14, Riyadh",
    latitude: 24.8150,
    longitude: 46.6120,
    images: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=600&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=600&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&auto=format&fit=crop&q=80"
    ],
    createdAt: "2026-05-29T12:45:00Z",
    isApproved: true
  },
  {
    id: "prop-20",
    title: "Triplex Crown Penthouse at Porto Arabia",
    description: "Commanding 360-degree vistas over the sparkling West Bay and luxury yacht marinas. Equipped with hand-finished Calacatta gold marble, custom Italian designed kitchens, automated blinds, and a private sky deck with integrated bar.",
    type: "sale",
    pricePerSqm: 16000,
    totalPrice: 7200000,
    area: 450,
    country: "QA",
    district: "The Pearl-Qatar",
    bedrooms: 4,
    phone: "+97444112233",
    address: "The Pearl Marina Promenade, Tower 31, Doha",
    latitude: 25.3725,
    longitude: 51.5510,
    images: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1512915922686-57c11dde9b6b?w=600&auto=format&fit=crop&q=80"
    ],
    createdAt: "2026-05-29T15:10:00Z",
    isApproved: true
  },
  {
    id: "prop-21",
    title: "عمارة تجارية استثمارية بالكامل في الحمراء",
    description: "فرصة كاداستر استثمارية ذات طابع خاص وعوائد آمنة ومضمونة. مبنى حديث بإدارة تقنية وبنية تحتية كاملة مرخصة ومؤجرة بالكامل لمنشآت تجارية عريقة.",
    type: "sale",
    pricePerSqm: 12500,
    totalPrice: 11250000,
    area: 900,
    country: "SA",
    district: "Al-Hamra, Jeddah",
    bedrooms: 12,
    phone: "+966555544321",
    address: "تقاطع شارع الحمراء التجاري الرئيسي مع طريق الأندلس، جدة",
    latitude: 21.5186,
    longitude: 39.1625,
    images: [
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=600&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=600&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=600&auto=format&fit=crop&q=80"
    ],
    createdAt: "2026-05-29T19:22:00Z",
    isApproved: true
  },
  {
    id: "prop-22",
    title: "Sentosa Cove Oceanfront Bungalow",
    description: "Ultra-luxury waterfront mansion in Singapore's exclusive Sentosa Cove. Private yacht berth, absolute privacy, 20-meter infinity pool, and custom architectural glass facades with panoramic South China Sea views.",
    type: "sale",
    pricePerSqm: 38000,
    totalPrice: 19000000,
    area: 500,
    country: "SG",
    district: "Sentosa Cove",
    bedrooms: 5,
    phone: "+6561234567",
    address: "Cove Drive, Sentosa Island, Singapore",
    latitude: 1.2435,
    longitude: 103.8421,
    images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=600&auto=format&fit=crop&q=80"],
    createdAt: "2026-05-30T09:00:00Z",
    isApproved: true
  },
  {
    id: "prop-23",
    title: "Belgravia Classic Heritage Mansion",
    description: "An extraordinary Grade II listed late-Georgian townhouse in London's premier residential area. Meticulously restored to combine breathtaking historic ceiling moldings with high-tech automated subterranean security, gym, spa and staff quarters.",
    type: "sale",
    pricePerSqm: 45000,
    totalPrice: 27000000,
    area: 600,
    country: "GB",
    district: "Belgravia, London",
    bedrooms: 6,
    phone: "+442079460192",
    address: "Eaton Square, Belgravia, London",
    latitude: 51.4981,
    longitude: -0.1512,
    images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&auto=format&fit=crop&q=80"],
    createdAt: "2026-05-30T10:15:00Z",
    isApproved: true
  },
  {
    id: "prop-24",
    title: "Yorkville Smart Penthouse Sky Residence",
    description: "Sophisticated modern top-floor sky mansion in Toronto's ultimate design sector. Features 12-foot floor-to-ceiling windows, wrap-around heated terrace, customized Italian cabinetry, Gaggenau kitchen, and direct private elevator transit.",
    type: "sale",
    pricePerSqm: 22000,
    totalPrice: 5500000,
    area: 250,
    country: "CA",
    district: "Yorkville, Toronto",
    bedrooms: 3,
    phone: "+14165550199",
    address: "Bloor Street West, Yorkville, Toronto",
    latitude: 43.6702,
    longitude: -79.3912,
    images: ["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&auto=format&fit=crop&q=80"],
    createdAt: "2026-05-30T11:45:00Z",
    isApproved: true
  }
];
